### ISSUE TITLE
Prepopulate username

### ISSUE THREAD

**Issue by twocanoes** [twocanoes/xcreds#104]
Define a element to save / repopulate so user doesn't have to type their name each time.

**Comment by Mavyre** [comment]
Alternatively, we could have an option wich switches the "Go to mac Login" to go to the real MacOS login screen, with the user selection.

**Comment by twocanoes** [comment]
If you command click the switch login button, it will take you to the mac login window.

**Comment by Mavyre** [comment]
@twocanoes Roadmapped for 3.3?
