### ISSUE TITLE
Log shows tperfitt user profile path

### ISSUE THREAD

**Issue by johnyoakum** [twocanoes/xcreds#108]
In the log located at /tmp/xcreds/xcreds.log it shows some paths to tperfitt's user profile. See line items below:

authorizationhosthelper.arm64(84759): -[XCredsLoginPlugin MechanismCreate:EngineRef:MechanismId:MechanismRef:] /Users/tperfitt/Documents/Projects/xcreds/XCredsLoginPlugIn/XCredsLoginPlugin.m:110

authorizationhosthelper.arm64(84759): MechanismInvoke /Users/tperfitt/Documents/Projects/xcreds/XCredsLoginPlugIn/XCredsLoginPlugin.m:42 id:CreateUser

authorizationhosthelper.arm64(84759): XCredsBaseMechanism.swift:129 allowLogin() allowLogin() /Users/tperfitt/Documents/Projects/xcreds/XCredsLoginPlugIn/Mechanisms/XCredsBaseMechanism.swift:129

As much as this doesn't bother me, I know that my team and those that may evaluate the logs (security) might have a fit about it since this user does not exist on our system.

**Comment by Mavyre** [comment]
Same goes in the build.sh, which checks and wants to execute a packager script within `/Users/tperfitt/Documents`
