### ISSUE TITLE
CreateAdminIfGroupMember

### ISSUE THREAD

**Issue by mlovingtwocanoes** [twocanoes/xcreds#115]
“CreateAdminIfGroupMember” not currently work for AD but only for cloud login

**Comment by aahbane-jd** [comment]
Same issue here, I tried it with Azure Ad group as shown in this video ( https://www.youtube.com/watch?v=JWzkZfhShxQ ); my user is part of the group and still when I login in the first time XCreds create the user as standard user.

**Comment by thenebular** [comment]
I'm having the same issue with Azure. I followed the instructions in the video and the user is still being created as a standard user despite being in the designated group.

Looking at the logs it seems that xcreds is not getting any group information about users from Azure. I added groupMember.Read.All permissions to the enterprise app and it did not make a difference.

**Comment by twocanoes** [comment]
i tested in Azure and it is working for me. in 3.3, i changed it to make admin anytime you add to the admin group. can you test the latest prebeta of xcreds 3.3?

**Comment by twocanoes** [comment]
closing. please reopen if it doesn't work for you
