### ISSUE TITLE
Feature Request: Show / Hide the switch login button with a pref key.

### ISSUE THREAD

**Issue by edbobak** [twocanoes/xcreds#121]
Using xcreds in the computer labs students are switching to the local login vs the 365 login screen for some reasons.  Can we get a pref key that hides the switch login button but some key combo (like command + option + shift + l) does the switch for local techs to use?

**Comment by twocanoes** [comment]
won't the students figure it out? How about a pref to prompt for local admin when clicking the login window button?

**Comment by edbobak** [comment]
Oh I think we are ok with them finding out over time.  It just stops them from doing it now so they get used to login with their email and not username.   Having it locked to local admin might be weird as you'd have to put in a fun pw twice to get to a desktop.
