### ISSUE TITLE
Feature request: xcreds login “lite” ROPG

### ISSUE THREAD

**Issue by lapster81** [twocanoes/xcreds#122]
This is a xcreds login “lite” feature request. In contrast to webview, only email and password at loginwindow for user creation utilizing ROPG. would also be nice to set how many accounts can be created this way per computer. For 1 to 1 computers email could be prefilled ( locked or editable)  from a configprofile

**Comment by twocanoes** [comment]
not sure how many people will use this. what is this important over a web view?

**Comment by lapster81** [comment]
A choice is always nice to have.

The name ( now email ) and password logon fields are recognisable for many as its the same way we logged in using AD for decades.

From a gui perspective what i have seen this is how ms/apple psso will look like in apples loginwindow, in current state that does not work for the first user account but after registration for all user creation after the first, this is where xcreds could come in for that first one before registering with company portal psso.

ropg is already used for password sync in xcreds, adding this for logging in / user creation could be a super clean look. 

From secutity standpoint we are already talking about an enrolled machine so combined with conditional access it can also be something you have with something you know fulfilling at-least 2fa. Adding that its only local access, for wan services we are already promted enough with the web view 😀

**Comment by twocanoes** [comment]
this is enabled in beta 3 of version 4.
