### ISSUE TITLE
feature request: localad/kebereros support for saving groups to prefs 

### ISSUE THREAD

**Issue by bamtan** [twocanoes/xcreds#125]
similar request to #117 - this was something already implemented in nomad, where it stored all the `memberOf` results into the preference file on run.

https://github.com/jamf/NoMAD/blob/6200f60f267b5fc725728b088e0ff6ad752d6f24/NoMAD/UserInformation.swift

**Comment by twocanoes** [comment]
saves into local ds record as _xcreds_groups as a string with groups separated by a comma.
