### ISSUE TITLE
[bug] Build 6026 - Cloud Login - Options Not Centered

### ISSUE THREAD

**Issue by dufto** [twocanoes/xcreds#131]
A minor Inconvenience.

As seen in the screenshot below; Options on the bottom of the Cloud Login Window are showing on the left side of the display instead of the center.

![Screenshot 2023-12-14 at 10 01 31 AM](https://github.com/twocanoes/xcreds/assets/53312077/22df8e9d-1db2-4043-a4c3-a574eee7b644)

**Comment by twocanoes** [comment]
fixed in the next build.

**Comment by dufto** [comment]
Thank you @twocanoes !
