### ISSUE TITLE
Password reset dialog rendering and text need fixes

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#133]
v4.0 build 6023

For issue #123 regarding password reset, the dialog shown asking to enter local login password provides a button to allow an admin to reset the user's password.  The text of the dialog, however, currently describes the prior recommended fix to have the admin log in separately and reset the user's password.  It may be better if this text is revised to mention the Reset button now available.  

Also when clicking the Reset button the next dialog window shown appears to be cut off slightly at the top.  

After that, though, everything looks good and the feature performs as expected to reset the password.

**Comment by twocanoes** [comment]
changed to "If you do not know your local login password, click Reset and enter in a local admin usern and password."

as for the cut off, that is due to a sheet on top of a small window. Not sure what to do about it. grumble grumble.
