### ISSUE TITLE
keyboard / mouse

### ISSUE THREAD

**Issue by tperfitt** [twocanoes/xcreds#135]
XCreds can cause the mouse/keyboard to reject any input until a full power-cycle of the machine has been performed. From what we have gathered, it seems that the users are having to repeat this process multiple times throughout the day, causing major delays in their workflow. The machines that have this happen are an M3/Sonoma machine and an Intel/Big Sur machine, and both will have this bug occur after a restart, the screen saver turning on, and when the machine sets itself to sleep.

**Comment by twocanoes** [comment]
I believe this was related to focus and resolved.
