### ISSUE TITLE
Problem with AD user sign in after password change

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#137]
v3.2.1 build 6002

When signed in as an AD user and using Ticket Viewer to change password, there appears to be an issue when signing out and signing in again with the new password.  When the new password is entered in the XCreds local login screen the screen goes black for several seconds and then returns without signing in.  If the old password is then entered, sign in succeeds normally.

**Comment by twocanoes** [comment]
please test in v4 and reopen if still happens
