### ISSUE TITLE
Login screen hangs after AD user sign in with recently changed password

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#139]
v4 build 6097

When an AD user signs in and uses Ticket Viewer to reset their password, if the user then signs out and tries to sign in again the XCreds login screen will hang right after entering the new password and never load the desktop.  The user can instead sign in after checking the offline authentication option and then sign in using the old password.  

The XCreds menubar app was running when using Ticket Viewer to reset the password.

**Comment by twocanoes** [comment]
tested in 6201. I think i may have fixed it as a side effect of something else. please test again.
