### ISSUE TITLE
Trouble with setting AD user as admin when group member

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#140]
v4 build 6097

CreateAdminIfGroupMember does not make the user admin for an AD user assigned to a group with matching group name.  This appears to be related to `_xcreds_oidc_groups` vs `_xcreds_groups` in Directory Utility.  

No problem when setting Azure user as admin when group member.

**Comment by davelebbing** [comment]
Log from example

**Comment by rfleischmann** [comment]
There are two school districts that I am working with that are still using NoMad and NoMad Login. The AD group for macOS admin assignments is a big must. Still using onprem AD but "slowly" moving to AZURE.

**Comment by twocanoes** [comment]
tested and worked fine. see attached profile for sample.
[xcreds-AD Only_admin_group.mobileconfig.zip](https://github.com/twocanoes/xcreds/files/13807202/xcreds-AD.Only_admin_group.mobileconfig.zip)
