### ISSUE TITLE
[Feature Request] AD group member login/denial

### ISSUE THREAD

**Issue by bronson-bohnet** [twocanoes/xcreds#144]
Since groups are returned with AD login, and utilized in `CreateAdminIfGroupMember`, I would like to see the ability to use a restrictive/allowable login. 

This could be something as simple as `DenyLoginIfGroupMember` and/or `AllowLoginIfGroupMember` followed by allowing/denying based on AD group membership. This could add some delay in login based on how many groups an account is a member of, so if possible to have it check "if null don't verify" would allow for a quicker login if setting not used, if necessary.

I don't know if it would be necessary to have a "denial message" of some sort, but I can see the use case for having that as well, if anything just a page view with "You do not have permission to access this machine". 

Scenario: Public computers which are accessible by a "Guest" AD user, and a lab that is accessed by "Assigned" AD users in roughly the same area. This setting would allow for less confusion on which machines are available to which individuals, denying a "guest" login on the lab machines and denying a "assigned" login on the public machines if wanted.

**Comment by twocanoes** [comment]
There is already a key from NoMAD : "DenyLoginUnlessGroupMember" that should work but is not currently docuemented. Will that suffice?

**Comment by twocanoes** [comment]
please open if not
