### ISSUE TITLE
Admin status does not change after removed from group

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#145]
v4 build 6204

For an Azure user assigned to a group, the CreateAdminIfGroupMember key will give them admin status as intended but when the user is removed from the group in Azure it will not change their admin status after next XCreds sign in or macOS restart.

Related to issue #109, refactored code to add admin to user account based on group membership each login

**Comment by twocanoes** [comment]
this is as expected since removing admin can cause issues and I don't think tracking which users were made admin by xcreds and which admins are valid is a good approach. Closing.

**Comment by davelebbing** [comment]
Could be good to clarify this in manifest description that admin status is only added but not removed based on group membership.  

Current manifest description for CreateAdminIfGroupMember:

List of groups that should have its members created as local administrators. Set as an Array of Strings of the group identifier.

Proposed description change:

List of groups that should have members be given local administrator status.  Local administrator status can be given on first authentication when account created, or on later sign in of existing user when a group member.  Administrator status not removed if group membership later revoked.   Set as an Array of Strings of the group identifier.
