### ISSUE TITLE
[Feature Request] AD - Option to hide Sign-In menu item

### ISSUE THREAD

**Issue by bamtan** [twocanoes/xcreds#150]
Using Local AD with Beta 5 build 6261.

XCreds.app is launched on log-in, grabs Kerberos ticket without any user-input. Lab deployment.

The end user doesn't need to sign-in or re-sync password using the 'Sign In' feature, as Keychain Reset/Overwrite PW Silently is enabled in the configuration. Would prefer hiding this sign-in menu item.

**Comment by twocanoes** [comment]
added new key shouldShowSignInMenuItem
