### ISSUE TITLE
[Feature Request] System Info on XCreds Login Window

### ISSUE THREAD

**Issue by bamtan** [twocanoes/xcreds#154]
Similar to NoMADLogin-AD, having the option to display system info on the login window would be great, and is beneficial in a lab environment. 

Clicking on the System Info text would also cycle between hostname, serial, MAC, version, IP address. 

https://github.com/twocanoes/xcreds/blob/eaf319e143d9b6d25270981c7acb0f050506902b/NomadLogin/UI/SignInWindowController.swift#L365-L383

**Comment by PeetMcK** [comment]
Big +1 from me. This has always been one of my favorite QoL features at the login window. If someone is on a business network can't login, but can pull the computer name, IP, or serial it can speed reaching the computer and providing support.

**Comment by notverypc** [comment]
This would be great for us as well.

**Comment by twocanoes** [comment]
Looks like this: 

![LWScreenShot 2024-06-09 at 12 48 47 AM](https://github.com/twocanoes/xcreds/assets/1682630/c3460096-6866-4036-b553-de05cfd1ac60)

**Comment by twocanoes** [comment]
![LWScreenShot 2024-06-09 at 12 48 47 AM](https://github.com/twocanoes/xcreds/assets/1682630/ecb24108-af70-4e91-804d-eb5c0e32bbe6)

**Comment by twocanoes** [comment]
![LWScreenShot 2024-06-09 at 12 53 57 AM](https://github.com/twocanoes/xcreds/assets/1682630/50283b6b-0f32-4ab0-999d-c536a4901d8b)

**Comment by twocanoes** [comment]
nice idea. i added this key:

systemInfoButtonTitle
The title of the button for system info in the bottom right corner of the login screen. This can either be plain text or one of these special values: .os, .hostname, .ipaddress, .serial, .mac, .computername, .ssid. Using the special value will populate the associated infomation as the button title.

**Comment by uurazzle** [comment]
Hi:

How about providing options to pin items based on available space or font size?

Or options to implement custom text based on the script? Like checking > 30 days, OS updates available, etc. or many other options based on the needs of the organization using Xcreds. Also, would this support emojis to give other options outside font color to highlight important items, etc?

Like for example
🛜 SSID: [SSID]
🏷️ Name: MAC1234

**Comment by davelebbing** [comment]
Filing a new bug with info from previous comment

**Comment by davelebbing** [comment]
@twocanoes I believe `systemInfoButtonTitle` functionality from this issue is now complete for v5.0 and testing shows success.  Any new functionality described here to be addressed in new issue #255 so marking this issue as closed.

**Comment by uurazzle** [comment]
HI @davelebbing :

Thanks for the update. Is there an option to always so the system info or is manually clicking the button the only option currently?

**Comment by davelebbing** [comment]
@uurazzle that's right.  Clicking for info is currently the only option.
