### ISSUE TITLE
[Feature Request] Standard wallpaper options for default background

### ISSUE THREAD

**Issue by PeetMcK** [twocanoes/xcreds#155]
I'd like to match the M365 login background with the local default background so there can be a design thread maintained between the loginwindows. The M365 background behaves as "Fill Screen", but Xcreds Behaves as "Stretch to Fill Screen". This works without much of an issue with 16x9 and 16x10 screens but does not work well at all on other dimension screens like ultra-wide and portrait. 

Could we please get an option for "Fill Screen" along with the default "Fit to Screen"? 

You may want to consider mirroring the same default choices that the OS offers: "Fill Screen" (OS Default), "Fit to Screen", "Stretch to Fill Screen" (Xcreds default), and "Center".  I'm sure someone could make a case for "Fit to Screen" and/or "Center".

**Comment by twocanoes** [comment]
added new key shouldLoginWindowBackgroundImageFillScreen

**Comment by PeetMcK** [comment]
Sveet. TY. I'll test soon.
