### ISSUE TITLE
Typos in manifest descriptions

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#156]
v4 build 6266

In the manifest the descriptions for the following preferences need fixes.

`allowUsersClaim`

The claim that contains the value **to** check for in the allowedUsersArray. Both must be defined.

`allowedUsersArray`

List of users that are allowed to log in. An empty array or undefined array means any user can log in as long their cloud credentials are valid. The preference allowUsersClaim must be defined to a claim in the idToken that ~~identifiers~~ **identifies** the users. For example, if the allowUsersClaim is set to upn and the allowedUsersArray is set to an array that contains fred@twocanoes.com and the upn of a logging in user is fred@twocanoes.com, they would be allowed to log in. barney@twocanoes.com would not.

`shouldPromptForADPasswordChange`

If the domain controller returns back that the password is expired or needs to be changed, prompt the user. If this is set to false, login will fail and ~~and~~ **an** error message will be shown.

**Comment by davelebbing** [comment]
Typo remains in description for `allowedUsersArray` and `shouldPromptForADPasswordChange`.  Replace with content below.

`allowedUsersArray`

List of users that are allowed to log in. An empty array or undefined array means any user can log in as long their cloud credentials are valid. The preference allowUsersClaim must be defined to a claim in the idToken that identifies the users. For example, if the allowUsersClaim is set to upn and the allowedUsersArray is set to an array that contains fred@twocanoes.com and the upn of a logging in user is fred@twocanoes.com, they would be allowed to log in. barney@twocanoes.com would not.

`shouldPromptForADPasswordChange`

If the domain controller returns back that the password is expired or needs to be changed, prompt the user. If this is set to false, login will fail and an error message will be shown.

**Comment by twocanoes** [comment]
this was fixed
