### ISSUE TITLE
PasswordOverwriteSilent does not prevent user prompt for password

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#160]
v4.0 build 6266

When setting PasswordOverwriteSilent to true the user is still prompted for local password after a password reset and successful cloud login with a cloud password different than the current local password.  

This was tested with a profile also containing these other prefs:  

1. KeychainReset: true
2. localAdminUserName: valid admin username
3. localAdminPassword: valid admin password

`<key>KeychainReset</key>`
`<true/>`
`<key>PasswordOverwriteSilent</key>`
`<true/>`
`<key>localAdminUserName</key>`
`<string>admin</string>`
`<key>localAdminPassword</key>`
`<string>twocanoes</string>`

**Comment by twocanoes** [comment]
the correct behavior is to prompt and when the user presses reset, it doesn't prompt for admin credentials. This was broken and fixed in the latest build.
