### ISSUE TITLE
[Feature Request] If enabled, allow local Guest user login

### ISSUE THREAD

**Issue by PeetMcK** [twocanoes/xcreds#167]
**Issue:** If enabled the for login, the local Guest user cannot login when Xcreds is enabled.

**Behavior:** Enable Guest User login in "Users & Groups". Attempt to log in as "guest" or "Guest" with no password at the XCreds local login. Denied login. 

**Expected:** Enable Guest User login in "Users & Groups". Attempt to log in as "guest" or "Guest" with no password at the XCreds local login. Allowed login.

**Use case:** Guest logins do still have their place. In my case almost exclusively for 3rd parties using AV macOS devices for presentations. It's nice to have a self-cleaning user that has all the limitations of "Guest" for this use case.

**Note:** I believe in the "before-time" when XCreds was only an overlay for "Cloud Login", guest worked without issue. I have some (probably) incorrect recollection that it also worked in early local XCred login window implementations. It seems like this maybe as simple as Xcreds not passing an empty password.

**Comment by twocanoes** [comment]
Do you mean at the mac login window? If so, then it still should work. Just hold command when clicking the Switch Login Window, and it will go to the macOS login window. The you can sign in as guest as you normally would.

**Comment by PeetMcK** [comment]
I'll try the CMD + click the login window. If the macOS login window is loaded, I'm sure Guest will login. 

That said, is there a reason why 'guest' without a password should not or cannot work on the XCreds local login window?  While it can be explained/trained it does make the most sense to allow anything that would work at the macOS loginwindow (that's in /Local/Default) to work at the XCreds local window.

**Comment by twocanoes** [comment]
I agree, but I'll need to hook it up.

**Comment by PeetMcK** [comment]
Thank you in advance. The CMD + click has quieted the drum beat, but looking forward to this one getting rolled in!

**Comment by twocanoes** [comment]
looks like the guest account that gets created cannot be removed, at least apple silicon. closing at NTBF since not sure how we can get around Secure Token. If you can verify it worked in a prior version on Apple Silicon, please re-open.

**Comment by PeetMcK** [comment]
So the "before times" when this worked was pre the Xcreds local login window. That is, I've never been able to pass "guest" with no password with the Xcreds local login window. All that said, I think I might be lost on the issue here. Guest shouldn't require a secure token. And this all really only works in any sort of sane way if FileVault is off anyway. The Guest experience with FileVault on is not ideal for a media/conference room computer.
