### ISSUE TITLE
Admin user set to Standard user on Local Login

### ISSUE THREAD

**Issue by bstep1** [twocanoes/xcreds#173]
User is created as an admin upon first login while on the network determined by their AD / OID claim Membership.  If Offline Authentication is then selected, the user is demoted to a standard user.

Expected behavior: User remains an Admin unless they get removed from an AD / OID claim.  Shouldn't demote / promote while offline, instead the groups are read upon successful AD/OID Login and then demoted/promoted.

**Comment by twocanoes** [comment]
fixed in PreBeta-XCreds_Build-6359_Version-4.1. please verify.

**Comment by bstep1** [comment]
Worked!  Admin user remains Admin now logged in locally on PreBeta-XCreds_Build-6359_Version-4.1.
