### ISSUE TITLE
[Feature Request] Local User Behavior

### ISSUE THREAD

**Issue by bstep1** [twocanoes/xcreds#174]
On the AD Login Window if the account is not found in the LDAP Lookup as it is a local only account, currently the behavior is to check "Offline Authentication" to allow the user to login.  

Would like a preference to be created to change the behavior named something like -localUserFallback.

I would like this feature to do two things, one if the Domain is available, it will fallback to local only for a truly local account.  If the Domain is not available, then  an AD User that had previously logged in to the computer could login locally without having to use the Offline Authentication Checkbox.

**Comment by twocanoes** [comment]
There is an undocumented key that does that:

LocalFallback

Set it to true and see if it has the behavior you want:
<key>LocalFallback</key>
<true/>

**Comment by bstep1** [comment]
This feature doesn't appear to be working.

I added the following to my mobileconfig file: 
<key>LocalFallback</key>
<true/>

However the behavior did not work.  I tried my local only account without checking the box for "Offline Authentication" and received:

Client (username@domain.net)
unknown

I also tried another attempt after removing "Show Local Only Checkbox" from the preferences, but it also failed local login unless I check the "Offline Authentication".

**Comment by bstep1** [comment]
Ok, this is actually working, but a little differently then I had hoped.  Apparently this means if Domain is unavailable, fallback locally. 

This actually is the behavior I would like for the most part, but also an account that exists locally only (Non AD Account would also be accepted when the domain is reachable.)

**Comment by twocanoes** [comment]
try build 6374 that i just posted. I think it now works as you expected.

**Comment by bstep1** [comment]
:) Thanks Tim, works great!

**Comment by dstranathan** [comment]
I am testing this behavior and it appears to working for me. 

Now Im debating on if I need to show the "Offline Auth" checkbox at all - can you think of a reason to keep the manual box if XCreds can 'intelligently' and dynamically determine the state of the AD domain?

I added a Feature Request ([180](https://github.com/twocanoes/xcreds/issues/180)) that may be a duplicate. I apologize!
