### ISSUE TITLE
[Feature Request] Add option to customize the Refresh Banner text

### ISSUE THREAD

**Issue by dstranathan** [twocanoes/xcreds#176]
It would be nice to customize the text in both the window header and the text of the Change Passord >  Refresh Banner UI.  Currently, it shows these 2 strings:

Window Header: "XCReds Password Update"
Banner: "Your local account password needs to be changed to match your online password. Please authenticate now."

Id like to be able to add my org's name in these strings to brand it and make users more comfortable with trusting it. Plus, most users have no idea was "XCreds" is. Examples of what I might do:

Header: "<My org's> Password Update"
Banner: "Your local password needs to be updated to match your <Azure/AD/Org's> password.."

**Comment by twocanoes** [comment]
new preference added "refreshBannerText"
