### ISSUE TITLE
MFA issue when using Google authentication

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#177]
v4.1 build 6375

When using Google for authentication the user is prompted for a multifactor sign-in code at each sign-in event, even when selecting don't ask again on this device.

The user is asked to sign in immediately when launching the XCreds menubar app.  Both this sign-in and the main login screen ask for the multifactor sign-in code every time.  

After entering the MFA code the user is also asked every time to allow XCreds access to the Google account.

**Comment by twocanoes** [comment]
this has some security issues if we were to reconstitute cookies. closing as NTBF.
