### ISSUE TITLE
Allow user to use full name to sign in at XCreds username/password screen

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#178]

**Comment by Maarten-Wijnants** [comment]
+1 for this. We always told our users they can log in with 'Firstname Lastname'. In the default XCreds login window it's clear they need to use their email address. But in the local login window they now need to use firstname.lastname. This screen looks like a macOS screen, so probably should also act like a macOS screen and accept 'Firstname Lastname'.
