### ISSUE TITLE
[Feature Request] Customize the XCReds app's native login dialog box

### ISSUE THREAD

**Issue by dstranathan** [twocanoes/xcreds#179]
It would helpful to be able to add org-specific info/details to this dialog box. Id prefer to my org's name in the text to make sure users are comfortable entering creds into it. The current string mentions the work 'cloud' which is not accurate for my AD environment and may be confusing.

It would also be helpful to display the ID of the account that XCreds is prompting for.

It would also be nice to replace the default blue XCReds logo with my org's logo (or even just the patch to a local generic icon that users understand like Keychain Access etc)

<img width="490" alt="XCreds Swift app login prompt" src="https://github.com/twocanoes/xcreds/assets/1753240/2d23bcce-2863-490b-8ec3-8fad5e358329">

**Comment by twocanoes** [comment]
Added resetPasswordDialogTitle to change this. I'll add the username as well.
