### ISSUE TITLE
[Feature Request] Automatically failover to local auth when AD domain is not available

### ISSUE THREAD

**Issue by dstranathan** [twocanoes/xcreds#180]
AD login request:

Option to configure XCreds be 'aware' of the availability of the AD domain/realm before logging in.

-If reachable, then try to auth to AD first. 
-If not reachable, then fail-over to local auth. 

This would be an alternative to requiring the user _manually_ tick the "Offline Authentication" box in the XCReds login window overlay. To the end user, this proposed behavior would be similar to legacy AD binding (i.e. try AD _first_, then fall back to local - assuming the account exists in dscl).

 In my early demos to fellow IT staff, this has been high on the list of "why do I have to check this?" and "This feels like a step backward from AD binding"

![Offline Authentication checkbox](https://github.com/twocanoes/xcreds/assets/1753240/d337586b-e42a-480f-8281-f9bdeb76297e)

**Comment by twocanoes** [comment]
nothing for me to do here. Closing :)
