### ISSUE TITLE
Allow override of killall loginwindow in xcreds postinstall script

### ISSUE THREAD

**Issue by miawri** [twocanoes/xcreds#181]
The XCreds installer kills the loginwindow process as long as Finder is not running.  This breaks our bootstrap deployment workflow and will mean we would need to repackage each release.

Could the ability to override to the kill loginwindow in the postinstall script be implemented via control file?  

It would be great if the postinstall script could look for a static control file (Users/Shared/.xcredsPreventLoginWindowKill ?) and/or even better, a custom path value that would be read from the Xcreds profile at install time - this method would allow us to just specify a file that is present during bootstrap rather than put a control file in place ourselves.

e.g. 

```
# if Finder is not loaded or the control file does not exist, reload the loginwindow
if [[ /usr/bin/pgrep -q "Finder" ]] || [[ -f ${prevent_loginwindow_kill_flag_file} ]]; then
	exit 0
else 
	/usr/bin/logger "XCreds: Reload loginwindow"
	/usr/bin/killall -9 loginwindow
fi
```

**Comment by twocanoes** [comment]
not sure how to read from a config profile to override behaivior in an installer, so just putting in the hard coded /Users/Shared/.xcredsPreventLoginWindowKill
