### ISSUE TITLE
Map UID

### ISSUE THREAD

**Issue by twocanoes** [twocanoes/xcreds#186]
XCreds should be provide a way to map an OIDC or AD attribute for UID when creating the user account.

**Comment by mallej** [comment]
Hi,
in response to the [question in slack:](https://macadmins.slack.com/archives/C03GBF2DE7P/p1709843612458419?thread_ts=1707230452.347719&cid=C03GBF2DE7P)
The login should fail if the UID is already used.
The claim name should be configurable.
Thank you

**Comment by mallej** [comment]
look like a duplicate of https://github.com/twocanoes/xcreds/issues/74.
And yes, we are still interested in the function.
