### ISSUE TITLE
Make compatible with Crypt

### ISSUE THREAD

**Issue by twocanoes** [twocanoes/xcreds#188]
Fix issues with Crypt compatibility:

https://github.com/grahamgilbert/crypt

An undesirable double login. imagine it is possibly related to the fact that we use Crypt for FileVault enablement and escrow and the Xcreds loginwindow mechs are not seeing this? I am currently using the XCreds 4.1 build with Sonoma 14.4 in case it helps.

**Comment by miawri** [comment]
Hi Tim,

This was indeed a problem at my end with the security db not containing 'builtin:prelogin' mech in a test environment.  Once I'd added this alongside the Crypt and XCreds mechs, the double login vanished and passthrough worked as expected.

One thing the might be nice for you to add to the authrights tool would be a 'reset' option that resets the system.login.console mechs back to the current OS defaults in /System/Library/Security/authorization.plist

Anyway, all good.
