### ISSUE TITLE
Add Password expire date for OIDC (possibly in hybrid environments)

### ISSUE THREAD

**Issue by twocanoes** [twocanoes/xcreds#190]
We are in a hybrid identity situation with EntraID, so should the account also get password expiry info if there is line of sight to the On-Prem domain?

From here (https://learn.microsoft.com/en-us/entra/identity-platform/optional-claims-reference#v20-specific-optional-claims-set) the password expiry value looks to be `pwd_exp` in Entra ID, at least.

**Comment by miawri** [comment]
https://github.com/twocanoes/xcreds/issues/165

**Comment by twocanoes** [comment]
dup. fixed and closing.
