### ISSUE TITLE
[Feature Request] Allow custom default user icon for new users

### ISSUE THREAD

**Issue by miawri** [twocanoes/xcreds#191]
Newly provisioned user accounts are created with a random eagle/8 ball/lipstick user icon.

It would be good if this icon could default to an image file that could be specified in a preference item e.g.

defaultUserIcon = "/Library/User Pictures/Custom/userIcon.png"

Even better would be if it could be pulled from the idp if it exists - this may provide clues as to whether it is possible with XCreds against EntraID at least.

https://github.com/microsoft/shell-intune-samples/tree/master/macOS/Config/M365%20Profile%20Photo%20Sync

**Comment by twocanoes** [comment]
looks like this already exist:
UserProfileImage
Set that to a string that is a local path to a user 

(https://developer.apple.com/documentation/opendirectory/kodattributetypepicture)
The attribute type of the picture attribute, which specifies the path of the picture for each user displayed in the login window.
