### ISSUE TITLE
[Feature Request]  Option to continue to leverage a separate, discrete XCreds Shares profile (like NoMAD)

### ISSUE THREAD

**Issue by dstranathan** [twocanoes/xcreds#192]
Request to have the option of store all XCReds Shares data in its own dedicated profile (like NoMAD).

Having the XCreds Shares keys in the main XCreds profile is useful for those who want a single profile to manage, but may not be optimal for those of us who are managing a lot of business-critical SMB shares.

A couple reasons to consider offering a dedicated XCreds Shares profile:

1)  I have over 50+ shares to manage. It's messy when these keys are stored in the main XCreds profile.  I need ~7 keys per share = 350 lines of XML...that's a LOT of profile bloat!

2)  The likelihood of updating the main XCreds profile in production will be rare, (only once or twice year I hope), but my org adds SMB shares _several_ _times_ a year as new departments are added (we bring on new research labs, and each lab gets a SMB share which needs to be in XCreds). This means I may have to touch the XCreds profile more than Id like to. I want to avoid the potential for 'collateral damage' if something gets messed up in a main XCreds profile update. If a stand-alone Shares profile gets corrupted, sure, that's bad, but at least users can still manually mount a share, but but if the main XCreds keys are in a bad state then ALL of the XCReds login/sync keys might be missing/broken. Yikes.

Something to consider?

I realize that Tim added all Shares keys into the main XCreds profile for simplicity, but in my org's case, having 2 discrete profiles is more efficient, safe, and managable.

**Comment by twocanoes** [comment]
@davelebbing i believe you can put different settings in different profiles. Will splitting out the shares without changing the code work?

**Comment by dstranathan** [comment]
> @davelebbing i believe you can put different settings in different profiles. Will splitting out the shares without changing the code work?

It appears Tim will [address](https://github.com/twocanoes/xcreds/wiki/XCreds-5-Planned-Features) this option in XCReds 5.

"[Feature Request] Option to continue to leverage a separate, discrete XCreds Shares profile (like NoMAD) #192"

I am very appreciative of having this flexibility.

**Comment by twocanoes** [comment]
@dstranathan  This is Tim :). Dave does a lot of testing with separate profiles for XCreds at the same time, and I suspect that you can the same thing without any code changes.

**Comment by twocanoes** [comment]
I talked with dave and you can split out the shares as a separate profile and apply both.

tim
