### ISSUE TITLE
[Bug] Build 6175 - XCreds menu unresponsive after unmounting any drive

### ISSUE THREAD

**Issue by bamtan** [twocanoes/xcreds#194]
Experiencing this issue with XCreds build 6175. 

After unmounting any share drive location (e.g. mounted via XCreds share, or through an existing AppleScript) or even a local USB, the XCreds menubar becomes unresponsive with the beach ball wheel for some time.

MacBook Air M1 - macOS 13.6

**Comment by twocanoes** [comment]
having trouble replicating. please try in XCreds 5 beta and see if still happens.
