### ISSUE TITLE
shouldUseROPGForPasswordChangeChecking shows EntraID login box

### ISSUE THREAD

**Issue by miawri** [twocanoes/xcreds#196]
I wanted to use shouldUseROPGForPasswordChangeChecking for background password checks against EntraID and XCreds launches the EntraID login prompt rather than checking silently with cached credentials:-

KeychainUtil.swift:59 findPassword(serviceName:accountName:) Finding xcreds local password in keychain
KeychainUtil.swift:66 findPassword(serviceName:accountName:) xcreds local password found in keychain
KeychainUtil.swift:89 findPassword(serviceName:accountName:) 
TokenManager.swift:161 getNewAccessToken() 
TokenManager.swift:168 getNewAccessToken() Checking credentials in keychain using ROPG
KlistUtil.swift:155 klist() Tickets:[REDACTED]
KlistUtil.swift:155 klist() Tickets: [REDACTED]
KlistUtil.swift:155 klist() Tickets: [REDACTED]
PasswordUtils.swift:390 getLocalRecord(_:) Building OD query for name [REDACTED]
PasswordUtils.swift:253 localNode Finding the DSLocal node
PasswordUtils.swift:408 getLocalRecord(_:) Found local user: <ODRecord 0x600001b588a0 [attributes {'dsAttrTypeStandard:RecordType': 'dsRecTypeStandard:Users', 'dsAttrTypeStandard:GeneratedUID': 'C35641A4-02F0-42B4-BAFF-DC6A16D169D7', 'dsAttrTypeNative:name': '[REDACTED]', 'dsAttrTypeNative:_xcreds_oidc_family_name': 'Test1', 'dsAttrTypeNative:_writers_UserCertificate': '[REDACTED]', 'dsAttrTypeNative:passwd': '********', 'dsAttrTypeNative:_xcreds_activedirectory_kerberosPrincipal': '[REDACTED]@global.com', 'dsAttrTypeNative:_writers_AvatarRepresentation': '[REDACTED]', 'dsAttrTypeNative:realname': 'REDACTED', 'dsAttrTypeNative:_xcreds_oidc_username': '[REDACTED]', 'dsAttrTypeNative:authentication_authority': [';ShadowHash;HASHLIST:<SALTED-SHA512-PBKDF2,SRP-RFC5054-4096-SHA512-PBKDF2>', ';Kerberosv5;;[REDACTED];', ';SecureToken;'], 'dsAttrTypeNative:uid': '502', 'dsAttrTypeNative:record_daemon_version': '8980000', 'dsAttrTypeNative:_writers_picture': '[REDACTED]', 'dsAttrTypeNative:_writers_unlockOptions': '[REDACTED]', 'dsAttrTypeNative:_writers_jpegphoto': '[REDACTED]', 'dsAttrTypeNative:hint': '', 'dsAttrTypeNative:_xcreds_oidc_iss': 'https://sts.windows.net/be189d14-1d13-4148-9edf-47fff7e918a8/', 'dsAttrTypeNative:_xcreds_oidc_sub': 'REDACTED', 'dsAttrTypeStandard:AppleMetaNodeLocation': '/Local/Default', 'dsAttrTypeNative:picture': '/Library/User Pictures/Nature/Zen.heic', 'dsAttrTypeNative:_writers_hint': '[REDACTED]', 'dsAttrTypeStandard:ADUser': '', 'dsAttrTypeNative:_writers_passwd': '[REDACTED]', 'dsAttrTypeNative:home': '/Users/[REDACTED]', 'dsAttrTypeNative:_xcreds_creationDate': '2024-03-15T17:39:33Z', 'dsAttrTypeNative:unlockOptions': '0', 'dsAttrTypeNative:gid': '20', 'dsAttrTypeStandard:RecordName': '[REDACTED]', 'dsAttrTypeNative:accountPolicyData': '<CFData 0x14500ca50 [0x1fcc188c0]>{length = 416, capacity = 416, bytes = 0x3c3f786d6c2076657273696f6e3d2231 ... 2f706c6973743e0a}', 'dsAttrTypeNative:_xcreds_didCreateUser': '1', 'dsAttrTypeNative:shell': '/bin/zsh', 'dsAttrTypeNative:generateduid': 'C35641A4-02F0-42B4-BAFF-DC6A16D169D7', 'dsAttrTypeNative:AvatarRepresentation': ''}]>
ShareMounter.swift:225 getMountedShares() Currently mounted shares: 
REDACTED
ShareMounter.swift:263 getMountedShares() Volume: /, is not a network volume.
ShareMounter.swift:255 getMountedShares() Volume: /Volumes/REDACTED, is a SMBFS network volume.
ShareMounter.swift:266 getMountedShares() Mounted shares: [smb://REDACTED]
ShareMounter.swift:144 getMounts() No home mount dictionary
ShareMounter.swift:147 getMounts() evaluating Shares
ShareMounter.swift:169 getMounts() checking group membership for mounts
ShareMounter.swift:278 mountShares() Evaluating mount: REDACTED
ShareMounter.swift:291 mountShares() Skipping mount because it's already mounted.
MainController.swift:195 setup() 
TokenManager.swift:415 tokenResponse(tokens:) ======== tokenResponse =========
ScheduleManager.swift:18 tokenError(_:) authFailure: error gettings tokens
MainController.swift:351 credentialsCheckFailed()

Is this a misconfiguration on my end or is there a bug when using ROPG to check the password?

**Comment by twocanoes** [comment]
sounds like a misconfiguration. Please send a support email to support@twocanoes.com
