### ISSUE TITLE
[Feature Request] - Privilege Elevation via the XCreds menubar

### ISSUE THREAD

**Issue by CycleParm** [twocanoes/xcreds#197]
• Allow a standard user to elevate their privileges for a defined amount of time through the XCreds menubar item.  
• Provide a time remaining countdown timer

**Comment by everetteallen** [comment]
It would be very interesting to add functionality from SAP Privileges along with a true macOS timer  to help meet the community needs here.  What do you think Tim?

**Comment by twocanoes** [comment]
Any more information? How would this be allowed / disallowed? Via MDM?

**Comment by everetteallen** [comment]
I would add two keys to the configuration profile 
1) allowPrivilegeElevation Bool True/False that would activate the feature
2) privilegeElevationAllowGroup  String <whatever> would be the name of a Entra/Okta/Google/SCIM/etc group whose members are allowed to elevate privileges if allowPrivilegeElevation is true.  If this key is not set all standard users would be allowed to elevate.

**Comment by twocanoes** [comment]
why not just use SAP Privileges? So you have one less menu item?

**Comment by everetteallen** [comment]
Several reasons but the biggest is that Privileges does not have a reliable demotion mechanism and depends on deprecated launch agents and can be removed when the primary function of the app is executed.

**Comment by twocanoes** [comment]
Looks like the SAP Elevation is active and fits that need.
