### ISSUE TITLE
Feature Request: EnforceSignIn

### ISSUE THREAD

**Issue by float0n** [twocanoes/xcreds#199]
For the scenario where you're deploying XCreds to an existing fleet of users and do not want to leverage the login window functionality, it would be ideal to have a way to require the user signs in and syncs their Cloud IDP password down to their Mac via the XCreds menu bar app. Currently, this requires the user manually interacting with the menu bar and choosing to Sign in.

**Comment by twocanoes** [comment]
I'll add in a new preference key.
