### ISSUE TITLE
Support for Microsoft Azure SSO extension

### ISSUE THREAD

**Issue by dechkovanen** [twocanoes/xcreds#20]
Add SSO support for Microsoft Azure SSO plugin when xcreds bundle identifier is defined in SSO settings.

https://docs.microsoft.com/en-us/azure/active-directory/develop/apple-sso-plugin#enable-sso-for-all-apps-with-a-specific-bundle-id-prefix

**Comment by twocanoes** [comment]
This may already work. The refresh token is saved to the user keychain and then validated by the menu item, which uses a URLSession. If SSO plugin is configured, it may just work. please test.

**Comment by patthew** [comment]
@twocanoes in my testing this results in a blank white box I cannot interact with, rather than bypassing the auth prompt. Happy to supply logs if needed!

**Comment by chrisapplecom** [comment]
@twocanoes 

I saw the same results as @patthew in my testing too : )

**Comment by dufto** [comment]
Do we have any update on this one?

**Comment by 1sth1sth1ng0n** [comment]
In my testing the Microsoft Enterprise SSO plug-in web view does appear correctly when using XCreds app to change/refresh the password. 

You do need to have Company Portal installed on the device for the above to work.

<img width="921" alt="Screenshot 2023-05-31 at 20 06 07" src="https://github.com/twocanoes/xcreds/assets/90104938/9ce0235c-b4df-4a5a-93be-3618015c7a99">

**Comment by patthew** [comment]
@1sth1sth1ng0n what version are you running?

**Comment by 1sth1sth1ng0n** [comment]
Version 3.1 (4081)

**Comment by twocanoes** [comment]
Closing. please open if this doesn't work
