### ISSUE TITLE
Feature Request - Change the wording of the password change pop-up

### ISSUE THREAD

**Issue by notverypc** [twocanoes/xcreds#202]
Is there anyway to change the wording of the password change pop-up?
I've looked through the preferences document but didn't see anything.

The pop-up says "your cloud password", but as we're still using on-prem AD this will confuse our users.

Thanks
![2024-03-26_PasswordChange](https://github.com/twocanoes/xcreds/assets/585423/ce176152-a131-43a7-a0f0-e778fc84b23c)

**Comment by iamlenhall** [comment]
That would be a game changer for us!!! If we could use our own wording there it would tremendously help our users. It’s hard for them to remember that they need to enter their previous password to begin using their newly changed password. --Leonard HallOn Mar 28, 2024, at 11:11 AM, notverypc ***@***.***> wrote:﻿
Is there anyway to change the wording of the password change pop-up?
I've looked through the preferences document but didn't see anything.
The pop-up says "your cloud password", but as we're still using on-prem AD this will confuse our users.
Thanks
2024-03-26_PasswordChange.png (view on web)

**Comment by tperfitt** [comment]
add new key "resetPasswordDialogTitle"
