### ISSUE TITLE
AD mapping not working

### ISSUE THREAD

**Issue by twocanoes** [twocanoes/xcreds#204]
I'm also trying to change the value displayed in the menubar app for "Active Directory Username"

In the XCreds profile I've tried the following:
<key>map_username</key>
<string>shortName</string>
And
<key>map_username</key>
<string>sAMAccountName</string>

**Comment by twocanoes** [comment]
@davelebbing please investigate and add details if it is still happening, or close if works as exprected.

**Comment by notverypc** [comment]
Sorry - yes this is working as expected now. 
Thanks very muchly.
