### ISSUE TITLE
Preference/Key to show macOS version on loginwindow

### ISSUE THREAD

**Issue by bronson-bohnet** [twocanoes/xcreds#205]
Would like to see an option to either enable the macOS version showing on login window or having macOS version included in the `shouldShowVersionInfo` preference as well. This will be helpful in identifying computer versions from a quick glance on the login screen if your are doing physical inventory rather than logging in to the machine.

**Comment by uurazzle** [comment]
Hi:

I would like to suggest incorporating some features from past macOS LoginWindow into Xcreds. These features, such as HostName, SystemVersion, IPAddress, and LoginWindowText (which allows customizing the text displayed in the login window), would greatly enhance our ability to monitor systems physically and provide necessary information to end-users.

For instance, having the ability to display HostName, SystemVersion, or IPAddress on the login window could be invaluable for notifying users or IT staff about certain system details. Additionally, features like ShutDownDisabled and SleepDisabled would be beneficial for systems where powering on or waking up might pose an additional burden.

The documentation from Apple's developer website provides valuable insights into these features:

https://developer.apple.com/documentation/devicemanagement/loginwindow

**Comment by bronson-bohnet** [comment]
You are correct! Apologies on that, I will close this one out so we aren't duplicating the request.
