### ISSUE TITLE
Custom Mac login window key combo

### ISSUE THREAD

**Issue by bronson-bohnet** [twocanoes/xcreds#206]
Would like to have the ability to use either the default key combo for `shouldAllowKeyComboForMacLoginWindow` or somehow provide a different key bind so that it isn't the default. 

Could be as simple as saying "add a custom key before pressing Enter as the final key" or something similar as I'm not sure how difficult it would be to incorporate key combos with control, option, command, enter in a mobileconfig.

**Comment by twocanoes** [comment]
new key:
keyCodeForLoginWindowChange 

key code for shouldAllowKeyComboForMacLoginWindow. If not defined, it is return or enter. If this is defined, this key is used with control-option to switch to login window and command-option-control and this key is used to switch to Mac Login Window. Uses CGKeyCode (for example, enter is 76 and return is 36)
