### ISSUE TITLE
Add a preference to allow XCreds to prompt for all users (including local users)

### ISSUE THREAD

**Issue by btaitt47** [twocanoes/xcreds#208]
Prior to XCreds 4.1, our local users would be prompted to sign in to XCreds upon initial login when signing into a Mac. Our Macs are setup with FileVault, so with FileVault passthrough, they would turn on the computer, sign in via FileVault, and once at the desktop the local account would check with XCreds and we would see the green check meaning it was authenticated. 

Since 4.1 and a change to check if it was a local account, this has not happened and XCreds does not authenticate to our IdP at login through FileVault passthrough. Having a preference for this previous behavior would allow our users who log into their computers through FileVault to still be logged into XCreds, be prompted to sign in if they're not, and for password change checks to occur.

A link to a discussion on the issue is here: https://macadmins.slack.com/archives/C03GBF2DE7P/p1710434435486939

**Comment by twocanoes** [comment]
added new key: shouldShowMenuBarSignInWithoutLoginWindowSignIn
