### ISSUE TITLE
Enhancement request: Group Membership Zendesk Ticket 69193

### ISSUE THREAD

**Issue by mlovingtwocanoes** [twocanoes/xcreds#209]

**Comment by twocanoes** [comment]
allowedIfMemberOfGroup would be an
array of Group IDs and if the Entra ID  trying to login is a member of
any of thoses groups they can login regardless (including creating new
local account).  If a local account exists but the Entra Id is no longer
part of a group the login should fail.

**Comment by twocanoes** [comment]
added key allowLoginIfMemberOfGroup

**Comment by twocanoes** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>pfm_description</key>
	<string>List of groups that should have members be given local administrator status. Local administrator status can be given on first authentication when account created, or on later sign in of existing user when a group member. Administrator status not removed if group membership later revoked. Set as an Array of Strings of the group identifier.</string>
	<key>pfm_name</key>
	<string>allowLoginIfMemberOfGroup</string>
	<key>pfm_subkeys</key>
	<array>
		<dict>
			<key>pfm_name</key>
			<string>group</string>
			<key>pfm_type</key>
			<string>string</string>
		</dict>
	</array>
	<key>pfm_title</key>
	<string>Allow login if member of group. Empty array or not defined does not allow or deny based on group membership</string>
	<key>pfm_type</key>
	<string>array</string>
</dict>
</plist>

**Comment by everetteallen** [comment]
pfm_description is not accurate for this key and seems to have borrowed language from the key allowing group to be admin users.  Likely should read more like 
"List of groups whose members should be allowed to login. If the user is a member of any of these groups they can login regardless (including creating new local account) if authorization succeeds. If a local account exists but the user is no longer
part of a group the login will be denied. "

**Comment by everetteallen** [comment]
Profile manifest corrected in commit 25bed7f. Closing
