### ISSUE TITLE
Option to enforce account to log in

### ISSUE THREAD

**Issue by dechkovanen** [twocanoes/xcreds#21]
Since many/most(?) MDMs allow dynamic variables, it would be nice to have option to enforce the user name so that user cannot login with "wrong" account.

Basically a string key in config profile where one would put something like {{UserPrincipalName}}, %EMAIL% or whatever the MDM would then use to replace the value with user's UPN. Xcreds would then notice if that preference key is set, validate if it's an email address and if yes, automatically use that to login.

**Comment by twocanoes** [comment]
Is this so only a certain user is allowed to login to a specific computer?

**Comment by twocanoes** [comment]
no response. reopen if needed
