### ISSUE TITLE
Enhancement Request: XCreds app cant update ds

### ISSUE THREAD

**Issue by hydazz** [twocanoes/xcreds#212]
following on from https://macadmins.slack.com/archives/C03GBF2DE7P/p1713850151357849:

XCreds uses ds to store the kerberos and ad username/login, if one does not use xcreds login, these fields are not populated, and thus one cannot obtain a kerberos ticket, and the OIDC username is blank,
(easy fix via adding these attributes)
```
dscl . -create /Users/"${loggedInUser}" 'dsAttrTypeNative:_xcreds_oidc_username' "${loggedInUser}"
dscl . -create /Users/"${loggedInUser}" 'dsAttrTypeNative:_xcreds_activedirectory_kerberosPrincipal' "${loggedInUser}"@DOMAIN
```
suggested fix:
>xcreds should save that value in prefs and use that if it isn't in DS, but currently doesn't

**Comment by twocanoes** [comment]
added code to copy and update the same values in DS. You can read them with :

defaults read ~/Library/Preferences/com.twocanoes.xcreds.plist

and are all prefixed with _xcreds_
