### ISSUE TITLE
Setting HomeMountEnabled to false removes the home folder from the XCreds menuitems

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#213]
From ticket #70214

**Comment by twocanoes** [comment]
Setting HomeMountEnabled to false does stop the home folder mounting, but it also removes it from the XCreds menuitems.

Ideally we'd like user to be able to mount the home folder if required from XCreds.

**Comment by twocanoes** [comment]
home directory now shows up in the menu if defined in AD account, but only mounts if HomeMountEnabled is true.

**Comment by dstranathan** [comment]
Is there an option to hide the "Network Home" string from the drop-down menu?
