### ISSUE TITLE
XCreds Not getting Kerberos Tickets from check in

### ISSUE THREAD

**Issue by bgatestmg** [twocanoes/xcreds#214]
discussion is based here: 
https://macadmins.slack.com/archives/C03GBF2DE7P/p1716792682732949

When Logging into Mac Off Corporate Network through xcreds login screen, a kerberos ticket is not issued as it cannot talk to DC.

User connects to VPN, and XCreds does not gain a valid kerberos ticket at next check in, unless VPN is configured to stay connected when user logs out. To get a ticket the user needs to stay connected to vpn when logging out, then log back in to get a valid ticket. 

Would be ideal if it could get a new ticket at next check in(or ability to detect the presence of the domain and get a ticket when vpn is connected)

**Comment by twocanoes** [comment]
I looked a this and can't replicate. I start a network monitor and if the network changes and there is a network connection, the shares and kerberos tickets are checked and refreshed as needed. Can you try connecting and disconnecting for the VPN when XCreds is running in user space and then send me the log from ~/Library/Logs/xcreds.log?

tim

**Comment by bgatestmg** [comment]
sure thing

**Comment by bgatestmg** [comment]
<img width="363" alt="Screenshot 2024-06-13 at 8 10 33 AM" src="https://github.com/twocanoes/xcreds/assets/153768976/1566b8b8-614a-44d7-bd85-31ae470a2d5b">
i am working from home right now with a broken hand so easy test, ill report in at next check in with logs

**Comment by twocanoes** [comment]
Any updates?

**Comment by twocanoes** [comment]
closing due to lack of feedback.
