### ISSUE TITLE
Feature Request: NoLoAD-Style Progress Screen Support

### ISSUE THREAD

**Issue by PinkShellos** [twocanoes/xcreds#215]
To allow organizations who rely on the NoMAD Login DEPNotify progress screen for their deployment workflows, please include a feature that integrates a progress screen using SwiftDialog and/or DEPNotify as a login mech. 

Preferably, the mech should have options to run prelogin or postAuth (before or after the user signs in), and have the ability to hook into the MDM logs like DEPNotify can. 

Source: [NoLoAD Login Notify Wiki](https://github.com/jamf/NoMADLogin-AD/wiki/notify)

I think there could be improvements made to the overall functionality and usability of this feature, but just having it would go a long way to fully deprecating NoLoAD's use for this singular feature.

**Comment by twocanoes** [comment]
This really feels like it should be a feature of swift dialog:

https://github.com/swiftDialog/swiftDialog/issues/68

moving to xcreds future until i can investigate more.

**Comment by PinkShellos** [comment]
@twocanoes I see that support for this has been added via swiftDialog/swiftDialog#389, I'll go ahead and close out this issue. Thanks for investigating!
