### ISSUE TITLE
Notification when local password changed

### ISSUE THREAD

**Issue by dechkovanen** [twocanoes/xcreds#22]
There should be a notification after successful password change that says something like "You Mac password was changed to match your cloud password. Please note this the next time you are asked for the Mac password."

Optionally there could be a preference key to suppress the notification but it could be there by default.

**Comment by twocanoes** [comment]
Is this at the login window or when logged in? I assumed that if the user is prompted for their cloud password, that is enough for them to know the local changed. please reopen if not the case.
