### ISSUE TITLE
Menubar app crashes at launch for non XCreds user

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#225]
version 5.0 build 7056

When launching the XCreds menubar app as a macOS user that was not created by XCreds, the menubar app does not show in the menubar.  This does not appear to be affected by setting `shouldShowMenuBarSignInWithoutLoginWindowSignin` or leaving it unset.

**Comment by twocanoes** [comment]
caused by #https://github.com/twocanoes/xcreds/issues/223 fixed.
