### ISSUE TITLE
Enhancement Request "Mechanism to force xCreds to reevaluate Login Window Background Image"

### ISSUE THREAD

**Issue by macdude22** [twocanoes/xcreds#227]
It would be nice to have a mechanism to force xCreds to reevaluate the Login Window Background Image, loginWindowBackgroundImageURL.

Example scenario: Our marketing and communications department periodically asks my team to update various logos and iconography. Changing the file (but retaining the file name) linked via loginWindowBackgroundImageURL does not result in the local image being updated until the cached image file is removed from /Library/Caches/com.twocanoes.xcreds/

More broadly maybe there could be a mechanism to trigger xCreds to reevaluate all defined settings. 

See macadmins slack for additional discussion:

https://macadmins.slack.com/archives/C03GBF2DE7P/p1718226780880749

**Comment by twocanoes** [comment]
changed so that xcreds loads the background every time and saves it. It only uses the cache if the live load fails. Less bandwidth efficient, but always will use the current version on the intarwebs.
