### ISSUE TITLE
Update description for allowLoginIfMemberOfGroup

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#228]
v5.0 build 7066

The manifest description for allowLoginIfMemberOfGroup needs to be fixed.  It is currently the same as for CreateAdminIfGroupMember.

**Comment by twocanoes** [comment]
fixed

**Comment by davelebbing** [comment]
build 7087

Manifest shows a change to the title component for this but not for the description.  Description should be changed.
