### ISSUE TITLE
allowLoginIfMemberOfGroup not working as expected

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#230]
v5.0 build 7066

The key `allowLoginIfMemberOfGroup` does not appear to work as expected.  When I added it to a profile as follows and tried signing in as an Azure user who is not a member of the group `macadmin` I was able to sign in normally.  

<key>allowLoginIfMemberOfGroup</key>
<string>93392af1-8e10-4691-9702-a4d5e7f7c781</string>

**Comment by twocanoes** [comment]
please turn on verbose logging and send me the log from /tmp/xcreds/xcreds.log

**Comment by davelebbing** [comment]
Yep I had the config wrong.  I set it as a string instead of an array of strings.  Sign in blocked and allowed as expected once the profile was corrected.
