### ISSUE TITLE
keyCodeForLoginWindowChange not working as expected

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#231]
v5.0 build 7066

The key keyCodeForLoginWindowChange does not appear to work as expected. When I added it to a profile as follows and signed out, the normal key combination `control-option-enter` continued to work and the configured key combos for `control-option-tab` or `control-option-right-arrow` did not work.

```
<key>shouldAllowKeyComboForMacLoginWindow</key>
<integer>48</integer>
<!-- tab -->
<!-- <integer>124</integer> -->
<!-- right arrow -->
```

**Comment by twocanoes** [comment]
it is supposed to be used like this:

<key>shouldAllowKeyComboForMacLoginWindow</key>
<true/>
<key>shouldAllowKeyComboForMacLoginWindow</key>
<int>48</int>

**Comment by davelebbing** [comment]
I had this config wrong before but then fixed it and retested with same result.  Attached is the profile I used that was expected to enabled `control-option-right-arrow` to switch the login window.  Please let me know if I still have this wrong.
[v5.0-settings.mobileconfig.txt](https://github.com/user-attachments/files/15889724/v5.0-settings.mobileconfig.txt)

**Comment by twocanoes** [comment]
The attached profile worked for me; however, the default command worked as well. refactored code so only override works

**Comment by davelebbing** [comment]
Looks like arrow keys do not work for this but all others tested so far appear ok.  Not a problem but just noting for future reference.
