### ISSUE TITLE
XCreds 5: Unexpected behavior of IP & MAC info via XCReds login window 'System Info' 

### ISSUE THREAD

**Issue by dstranathan** [twocanoes/xcreds#232]
Noticing unexpected behavior when looking at IP and MAC info via System Info 

-If BOTH Wi-Fi and  Ethernet dongle interfaces are active, Xcreds only shows Wi-fi IP address (not both).

-If NO interfaces are active, XCreds still displays a 'ether' MAC address from macOS - which is misleading as someone might think the Mac has an active connection.

**Comment by twocanoes** [comment]
added multiple IPs if available and removed MAC
