### ISSUE TITLE
allowLoginIfMemberOfGroup causes screen rendering issue after blocking sign in

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#233]
v5.0 build 7066

The key allowLoginIfMemberOfGroup works as expected but after blocking an unallowed user the login screen appears to be rendered multiple times with a second offset layer visible.  
![LWScreenShot 2024-06-18 at 4 08 49 PM](https://github.com/twocanoes/xcreds/assets/2489330/849b5a55-7158-45fa-8520-7183118b2c2a)

**Comment by twocanoes** [comment]
fixed. verify and close.

**Comment by davelebbing** [comment]
Better but now after blocking sign in the Azure window is rendered up and to the right of where it was.  Profile is attached.  
[allowLoginIfMemberOfGroup.mobileconfig.txt](https://github.com/user-attachments/files/16515665/allowLoginIfMemberOfGroup.mobileconfig.txt)

**Comment by twocanoes** [comment]
fixed? Fixed!

**Comment by davelebbing** [comment]
Message shown when denying sign in has a typo.  Corrected version: 

The user is not allowed to log in because they are not a member of an allowed group.
