### ISSUE TITLE
XCreds 5: Password Change window & login window

### ISSUE THREAD

**Issue by dstranathan** [twocanoes/xcreds#234]
-Bug? The XCreds menubar app Sign-in window `refreshBannerText` key doesn't seem to work. I still see the default message: "Your local account password needs to be changed..." even though I have a custom string set for this. Im referring to XCreds menu item > Sign-in...> XCreds Passord Update window 

-Feature Request: The "Password Update" window header/title cant be modified.  It currently says "XCreds Password Update" . Id prefer to be able to customize this string to remove the word "Xcreds" as my end-users don't know what XCReds is and it would be nice to add my org's name to ensure that users know its not malicious. I think this is slated for XCreds 5?

-Bug? If the Mac is offline, sometimes my org's cached custom "Sign in" wallpaper (`menuItemWindowBackgroundImageURL`) is not used, rather the XCreds default blue wallpaper is rendered (i.e.: with the XCreds logo in bottom right).  I dont see any cached files for this image in /Library/Caches/com.twocanoes.xcreds associated with the URL key. 

I have also seen this behavior with the login window overlay a few times: I see the default macOS Sonoma wallpaper when offline,  not a cached version of my org's wallpaper (`loginWindowBackgroundImageURL`).  I do see a cached image file as expected in /Library/Caches/com.twocanoes.xcreds. One way to test this is to simply pull Ethernet from a Mac desktop running XCreds and  reboot. I see the macOS default wallpaper. Then I plug Ethernet back in and refresh the XCreds overlay. My custom wallpaper renders again. Stating the obvious, but my image is processed via a publically-readable URL -not locally.

**Comment by twocanoes** [comment]
worked for me. Added:

			<key>refreshBannerText</key>
			<string>abcasdfa asdf asdf asdf asdf asdf as dfads f</string>

![image](https://github.com/user-attachments/assets/132162f3-d622-4ddd-ab4c-bdc96e2c2d05)

**Comment by dstranathan** [comment]
I think I see what is happening. I have a group of test Macs using XCReds in AD only, and a set of Macs testing Azure/Entra + AD.

On the Azure/Entra Macs, the new` <key>refreshBannerText</key>` key is working. On the AD Macs it is not. Im using the same keys/values on both test group's profile. Example:

```
<key>shouldShowRefreshBanner</key>
<true/>
<key>refreshBannerText</key>
<string>Your local account password needs to be updated to match your Stowers cloud password.</string>
```

Screenshots:

Top = Entra + AD, bottom = AD only

<img width="1000" alt="Screenshot 2024-07-17 at 5 39 45 PM" src="https://github.com/user-attachments/assets/37498e93-41ed-4698-a73b-1ae2d2bd3644">

<img width="1025" alt="Screenshot 2024-07-17 at 5 39 06 PM" src="https://github.com/user-attachments/assets/56e2064c-fe27-4b42-a706-4efd4de3d95f">


Also, semi-related to this topic:  I may have misunderstood, but I was thinking that we would have the ability to remove "XCreds" in the window title bar (i.e. add our own custom string etc - users don't really now what XCReds is).

**Comment by dstranathan** [comment]
Update: The new customizable banner string is working as expected. The refreshBannerText key is functioning. Thanks.
