### ISSUE TITLE
[Feature Request] Display the XCreds version to the new "System Info" pop-up

### ISSUE THREAD

**Issue by dstranathan** [twocanoes/xcreds#235]
Low priority, but it would be nice to have the option to show the XCreds version into the new XCreds 5 System Info pop-up (`shouldShowSystemInfoButton`). One less key  to manage, and keeps the UI a little cleaner for those admins who choose to show the version at login. If I am choosing to enable the new 'show information on login window' option,  it seems reasonable to also add the XCReds version to the list along with OS version, IP, serial etc. Purely cosmetic, but worth mentioning.

**Comment by twocanoes** [comment]
added and moved system info to left side.
