### ISSUE TITLE
HomeMountEnabled remounts

### ISSUE THREAD

**Issue by twocanoes** [twocanoes/xcreds#238]
I've tested the updated "HomeMountEnabled" function in beta 5.0 (7066).

The home area does now show in the XCreds menuitem but once the drive is mounted, it will auto-mount if ejected.
Ideally the home are should only mount when selected, on-demand.

**Comment by twocanoes** [comment]
@davelebbing did you file this? So it doesn't automount but if it does, it automatically remounts?

**Comment by davelebbing** [comment]
This was not from me.  I can confirm, though, that the issue here is that the drive mounts normally, but if it is ejected it will remount immediately.  This may be undesirable and might be better if once ejected it does not immediately remount.

**Comment by notverypc** [comment]
I believe it was me that raised this issue. Unfortunately I’m unable to test this.

**Comment by twocanoes** [comment]
closing. please file again if this is replicatable.
