### ISSUE TITLE
Local login window dims and gets stuck after failed login attempt

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#242]
v5.0 build 7087

When using Azure and logging in at the XCreds local login window, if the login attempt fails the controls will dim and will not reset after the controls shake.  This can be worked around by switching the login window and then switching again to try another login attempt.  

<img width="594" alt="Screenshot 2024-06-24 at 4 35 32 PM" src="https://github.com/twocanoes/xcreds/assets/2489330/b09fa07e-8e0a-4663-858b-4f9ed590cc68">

**Comment by twocanoes** [comment]
Please verify

**Comment by davelebbing** [comment]
build 7105 works as expected
