### ISSUE TITLE
Issue with hideExpiration

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#243]
v5.0 build 7096

The key `hideExpiration` does not appear to work as expected.  When setting to true and launching the XCreds menubar app as an AD user, the item for `AD Password Expires` continues to be shown.

**Comment by davelebbing** [comment]
I'm still seeing AD Password Expires in the menubar app.  Profile is attached.  
[hideExpiration.mobileconfig.txt](https://github.com/user-attachments/files/16515877/hideExpiration.mobileconfig.txt)

**Comment by twocanoes** [comment]
The key is "HideExpiration" not "hideExpiration". Updated manifest.
