### ISSUE TITLE
Fail on map_username for AD

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#244]
v5.0 build 7096

When setting `map_username` to `sn` for an AD authentication environment it was not possible to sign in with the user's last name as expected.  This was for a user who was logging in for the first time on this setup.  Logging in the default way with the username did succeed and create a new user account.  The value for `sn` was confirmed to be shown as expected in the XCreds log after signing in.

**Comment by twocanoes** [comment]
please provide a profile or show sample.

**Comment by davelebbing** [comment]
The attached profile should allow an AD user to sign in with their last name as their user name when signing in for the first time, but instead the user continues to only be able to sign in with their default user name.
[xcreds 5.0 map_username.mobileconfig.txt](https://github.com/user-attachments/files/16394105/xcreds.5.0.map_username.mobileconfig.txt)
