### ISSUE TITLE
[Feature Request] Add macOS Guest Account button to login screen

### ISSUE THREAD

**Issue by jeremyclarke** [twocanoes/xcreds#246]
Please add an optional button to the XCreds login page bottom toolbar that enables easy login to the built-in macOS Guest Account, if enabled. Thank you.

**Comment by twocanoes** [comment]
You can log in as guest if you command click the "login window" button.

**Comment by jeremyclarke** [comment]
Hi, I was hoping you'd consider adding a button directly to the main XCreds bottom bar, instead of having to command-click, and then log in as Guest from the default macOS login screen.

![Screenshot 2024-07-26 at 09 26 24](https://github.com/user-attachments/assets/7c7b5a7b-41b4-4aeb-9d1e-0c03d382b612)
