### ISSUE TITLE
CreateAdminIfGroupMember - demoting user to standard once removed from group not working

### ISSUE THREAD

**Issue by jeremyclarke** [twocanoes/xcreds#249]
I'm successfully promoting my users to Administrators with the "CreateAdminIfGroupMember" functionality.
However upon removing users from the Azure AD group, users that were promoted are not demoted to Standard users again.
Users log out fully and back in via Cloud login. Users are not the last admin accounts left on the Mac.

I understood demotion to be a feature in XCreds 4.1. 

IDP: Azure AD
XCreds version: 4.1 6375
macOS: Sonoma 14.5

Thank you.

**Comment by davelebbing** [comment]
@jeremyclarke I just checked this on XCreds 4.1 / Sonoma 14.6 and CreateAdminIfGroupMember demoted the user as expected.  To clarify usage, XCreds will not demote if the user is the last XCreds admin user.  So to demote an admin user there needs to be another admin user that XCreds created or to which XCreds mapped an account.  If you are seeing differently please describe the user statuses involved.

**Comment by jeremyclarke** [comment]
Hi @davelebbing - thanks for clarifying. My remaining admin user was not created by XCreds. I can confirm I am now seeing the behaviour as you describe. It would be awesome if in the future XCreds could demote based on there being at least 1 other admin, created by XCreds or otherwise. Nonetheless, this feature helps a lot. Thanks for your time.

**Comment by twocanoes** [comment]
I think this is resolved. please file a new bug for the feature of demoting a non-xcreds admin.
