### ISSUE TITLE
Check Descriptions in Manifest to verify they match defaults in new code for 1.1(1276)

### ISSUE THREAD

**Issue by everetteallen** [twocanoes/xcreds#25]
>
         <dict>
                        <key>pfm_name</key>
			<string>shouldShowPreferencesOnStart</string>
			<key>pfm_type</key>
			<string>boolean</string>
			<key>pfm_title</key>
			<string>Show Preferences on Startup</string>
			<key>pfm_description</key>
			**<string>If no settings are specified, show preferences at startup</string>**
			<key>pfm_default</key>
			<false/>
		</dict>

Not sure the  pfm_description matches the default behavior in the code here please check

**Comment by twocanoes** [comment]
updated to match.
