### ISSUE TITLE
Update manifest description for CreateAdminIfGroupMember

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#251]
version 5.0

The manifest description needs to be updated to reflect that admin status is now removed when group membership is revoked.  

The description should also clarify that it will not demote if the user is the last XCreds admin user.  Currently if there is a local admin user that XCreds did not create, removing group membership for another user will not cause them to be demoted if the only other admin is the local-only admin.

**Current description:** 

List of groups that should have members be given local administrator status. Local administrator status can be given on first authentication when account created, or on later sign in of existing user when a group member. Administrator status not removed if group membership later revoked. Set as an Array of Strings of the group identifier.

**Proposed new description:** 

List of groups that should have members be given local administrator status. Local administrator status can be given on first authentication when account created, or on later sign in of existing user when a group member. Administrator status is removed if group membership later revoked.  Administrator status is not removed if user is the only XCreds admin user. Set as an Array of Strings of the group identifier.

**Comment by twocanoes** [comment]
verify and close if working.
