### ISSUE TITLE
Mac Login Window not swtching over

### ISSUE THREAD

**Issue by RetroRoscoe1** [twocanoes/xcreds#252]
Hi, when I click the 'Switch Login Window', I get a grey screen telling me to 'Please Wait or try connecting to network or check preferences'

**Comment by twocanoes** [comment]
This is most likely caused by the mobileconfig not scoped to "system".

**Comment by RetroRoscoe1** [comment]
Hi, it is scoped to computer not user in our MDM. Is there somewhere else this needs to be set then
<img width="1068" alt="Screenshot 2024-08-07 at 8 25 10 am" src="https://github.com/user-attachments/assets/f34f028c-68fc-4c97-89c9-33415d6b8189">

**Comment by RetroRoscoe1** [comment]
[com.twocanoes.xcreds.mobileconfig.zip](https://github.com/user-attachments/files/16516888/com.twocanoes.xcreds.mobileconfig.zip)
