### ISSUE TITLE
Cloud IdP Webview UI gets 'stuck' in lower left corner of XCreds login window

### ISSUE THREAD

**Issue by dstranathan** [twocanoes/xcreds#254]
I was asked to created this. Testing XCreds 5.0 build 7130

Entra IdP webview UI is off-center, towards the lower left corner of monitor.

-Typically happens after a full reboot.
-After a logout (not a reboot) I can sometimes catch the webview UI "snap" from bottom left to center.
-Clicking "Refresh" button doe not correct the issue.
-Toggling the XCreds "Switch Login Window" button back-and-forth DOES correct the issue.
-100% reproducible on a few test Macs (including 2 different MS Entra tenants, 2 OS versions)

See attached screenshot. I cropped it horizontally so it looks squished, sorry. But you get the idea.

![Screenshot 2024-08-07 at 11 27 49](https://github.com/user-attachments/assets/11dd532d-9622-4402-ab89-ff8c94e4d978)

**Comment by twocanoes** [comment]
please test in build 7141 or later.

**Comment by dstranathan** [comment]
I have tested on several Macs including in PreStage enrollments.  A colleague and I have seen the issue persist at least a 2-3 times each in testing. Always occurs after restarts for us (never after a logout that we are aware of). It's possible that we are seeing this issue less in 7141, not sure.

**Comment by davelebbing** [comment]
@dstranathan I tested this on build 7144 and it looks to be fixed.  If you see any problems remaining for this please add a comment.

**Comment by davelebbing** [comment]
@dstranathan please confirm if you are continuing to see the web UI login window get stuck in the lower left corner or if it is rendered there at first and then snaps to the center.  My testing has showed the window initially rendering off-center but then being corrected.

**Comment by dstranathan** [comment]
Just tested on 2 Mac laptops running 7147 at (2) different orgs (different JSSs, XCReds configs, and IdPs). Only happens after a full reboot for me.

**Comment by davelebbing** [comment]
@dstranathan, after reboot does the web UI window get centered after a period of time or does it permanently remain off center?

**Comment by davelebbing** [comment]
Confirmed replicating this issue on M1 MBA13 test machine.  When switching from web UI login screen to macOS login screen and then back, web UI gets stuck off center permanently.  @twocanoes is working on a fix for v5.0.

**Comment by dstranathan** [comment]
Sorry for delay. I was never able to get it to recenter on its own.

**Comment by davelebbing** [comment]
Build 7169 appears to fix this for my test example.

**Comment by dstranathan** [comment]
I installed Build 7176 on (6) Macs in 2 orgs and I haven't been able to reproduce it. Web ui is always centered for me now. Thanks.
