### ISSUE TITLE
shouldPromptForMigration issue

### ISSUE THREAD

**Issue by Maarten-Wijnants** [twocanoes/xcreds#258]
We noticed that during migration to XCreds the user is not prompted for their local credentials if their local account is an admin user (they become admin with Privileges https://github.com/SAP/macOS-enterprise-privileges). XCreds just creates a new account.

**Comment by davelebbing** [comment]
@Maarten-Wijnants please confirm the relevant mobileconfig settings used for this.  Are you never seeing an existing local admin account get used for migration and instead it always creates a new admin account?

**Comment by Maarten-Wijnants** [comment]
I didn't realize that the prompt for migration only works for standard user accounts. So this was expected behavior.
