### ISSUE TITLE
shouldShowQuit not honored in 1276

### ISSUE THREAD

**Issue by everetteallen** [twocanoes/xcreds#26]
Looks like shouldShowQuit is being ignored in 1276.
In MainMenu.swift at line 65 looks like key name needs to be changed but I could be reading the diff wrong:
 if UserDefaults.standard.bool(forKey: PrefKeys.shouldHideQuit.rawValue)==false{

thanks!

**Comment by everetteallen** [comment]
![Screen Shot 2022-07-01 at 2 56 15 PM](https://user-images.githubusercontent.com/5263924/176954453-30098d34-bbaf-423a-8244-e3e21372fe7e.png)

**Comment by twocanoes** [comment]
fixed in 3003. app was fine but sample profile manifest was incorrect.
