### ISSUE TITLE
Issue with 'Switch Login Window'

### ISSUE THREAD

**Issue by RetroRoscoe1** [twocanoes/xcreds#264]
Hi, everytime we click the 'Switch login Window' we get this screen...
![IMG_1003](https://github.com/user-attachments/assets/f5e84c8a-f636-459e-b520-b3afda4a504e)

What am I missing that is causing this behaviour, please?

**Comment by RetroRoscoe1** [comment]
Okay, thanks for the response. I guess I got confused about how to set up a local admin account login, like going back to the default Apple login screen.
On a side note, is there a way of setting extra text like I had in the Jamf Preferences for the different machine locations?
see examples
<img width="2560" alt="Screenshot 2024-08-30 at 8 15 26 AM" src="https://github.com/user-attachments/assets/fb0a10f0-ad53-4872-891d-c22add506d0c">
<img width="2560" alt="Screenshot 2024-08-30 at 8 15 08 AM" src="https://github.com/user-attachments/assets/d6ce0385-55ca-4b9d-902c-9cab02f8319e">

**Comment by davelebbing** [comment]
A local admin can log in from the same screen used for AD login but may need to click the offline authentication checkbox.  There are several preferences that relate to this in the admin guide: https://twocanoes.com/knowledge-base/xcreds-admin-guide/

Regarding extra text, I think you're looking for customization of menu features introduced in v4.1.  https://twocanoes.com/knowledge-base/whats-new-in-xcreds-4-1/

The upcoming release of v5.0 will also be adding customization options to show system info on the login screen using the preferences `systemInfoButtonTitle` and `shouldShowSystemInfoButton`.  https://github.com/twocanoes/xcreds/releases
