### ISSUE TITLE
If Apple Policy Banner configured Xcreeds login window continues to be blocked during login...

### ISSUE THREAD

**Issue by everetteallen** [twocanoes/xcreds#27]
If a Apple Standard policy banner is defined in  /Library/Security/PolicyBanner.txt the XCreds Login will continuously be blocked by reappearing Policy Banner.

**Comment by everetteallen** [comment]
See Slack discussion at
https://macadmins.slack.com/archives/C03GBF2DE7P/p1658328506213889

**Comment by gilburns** [comment]
I'm not suggesting that it doesn't work. It does. I'm just saying that if you are not quick to make it through the Azure login dialogs, the policy banner will start popping up over the top of your login. Doesn't break anything. Just annoying. :-)

**Comment by twocanoes** [comment]
It appears every 60 seconds for me and blocks xcreds. I believe this is expected behavior.

tim
