### ISSUE TITLE
XCreds banner when exiting out of encrypted preboot (sometimes indicating 14 day license expiration)

### ISSUE THREAD

**Issue by crgundersen** [twocanoes/xcreds#278]
XCreds version 5.0 and various macOS versions (e.g. 14.7 and 15.1 RC). Jamf JSON schema built from 5.0 compatible manifest. It's been noticed recently that XCreds will display banner at bottom of screen while exiting out of encrypted preboot, at times w/ added messaging about 14 day trial (we have working license file in place). This is only present for a brief period (1-2 seconds) and disappears. This isn't a blocking/breaking issue, but is aesthetically confusing should a user witness it. I've sent a log file via Slack. Slack discussion link/thread: https://macadmins.slack.com/archives/C03GBF2DE7P/p1727427941855859

![XCreds_Banner](https://github.com/user-attachments/assets/c66c6967-278d-4da3-947a-b68a20190e23)
<img width="324" alt="Jamf JSON Schema" src="https://github.com/user-attachments/assets/9dca8912-64b3-446f-9064-1a43ebe35e46">

**Comment by crgundersen** [comment]
Perhaps let some other folks test/validate as well before closing this out, but PreBeta-XCreds_Build-7261_Version-5.1 does indeed seem to correct this issue. Many thanks!

**Comment by twocanoes** [comment]
Not sure what changed, but closing :)
