### ISSUE TITLE
Request: Options to use xcreds as fallback auth method

### ISSUE THREAD

**Issue by bartreardon** [twocanoes/xcreds#31]
In my org our macs are mostly 1:1 assigned using local accounts and the Kerberos SSO extension for generating kerberos tickets.

For a user login workflow, it would be nice to be able to support the following:

1. Standard looking user/pass login window. Auth is passed to the OS and if successful then log in.
2. If auth is unsuccessful, and there is no local account with that username then defer to azure auth window. Unsure if this process is possible. It presumes the response can be differentiated from "valid username, wrong password" and "invalid username". It would not surprise me if all you can detect is "auth didn't work" in which case this workflow may not work at all.
3. successful auth creates the local account with that username. subsequent logins would follow step 1 flow

Not sure if this is possible of it I've explained it correctly. I can storyboard how I think it could look.

Essentially I would like the auth to be passing through Azure for initial account creation but then leave it up to the OS and KerberosSSO after that. Full azure login with MFA on a 1:1 device is currently a little tedious.

**Comment by bartreardon** [comment]
Actually been thinking about this for a bit and I think most of what I would like could be solved with a preferences that can be used to set the default login experience. (Checked https://github.com/twocanoes/xcreds/wiki/AdminGuide#preferences and there doesn't appear to be this option yet).

So my workflow would be, present cloud identity initially, but once the system owner is logged in and account created, update the preference key to change the default login window type.

if I can have an add on request, option to exclude certain account types from creating a local account. At the most simplistic level this could be setting a regex for exclusion from creating a local account (e.g. in our org, IT support accounts all start with the same prefix). Not sure how useful that might be elsewhere of if that type if thing is even done anywhere else but where I work 🤷)

**Comment by twocanoes** [comment]
Is this still needed? I can implement but it has been a while :)

**Comment by bartreardon** [comment]
Oh - forgot I put this request in. 

Not needed as the behaviour I was after is taken care of for "free" once filevault is enabled (assuming FV -> login passthrough).

In any case, not needed any more so I'll close. cheers 🙂
