### ISSUE TITLE
Request: option for branding

### ISSUE THREAD

**Issue by trekkim** [twocanoes/xcreds#32]
Hi , i would like to ask if will be possible create option for branding icons for App Icon or menubar icon. 
thx

**Comment by casban** [comment]
I'm not sure if it helps, but the SupportApp has the ability to use SF Symbols for a custom menu icon, perhaps that kind of thing would help?

https://github.com/root3nl/SupportApp/blob/69b14f9aff04cc3ec52a1f1a04db66a7df6ef6b6/src/Support/AppDelegate.swift
