### ISSUE TITLE
Request: option choose window size

### ISSUE THREAD

**Issue by trekkim** [twocanoes/xcreds#33]
Hi, option choose if normal or fullscreen for  Microsoft login window in login screen will be welcome.

thx

**Comment by twocanoes** [comment]
can you explain a bit more why you would want this? Is there something you want to put behind it?

**Comment by kcrawford** [comment]
In our case our login page is relatively short and vertically aligned to the top so it does not appear vertically centered as you’d expect for the macOS loginwindow. Visually it looks awkward. The larger the display the worse the vertical alignment looks.
One possibility might be a calculation based on display height and a configurable percentage offset from the top to be the top coordinates of the WebView. Not sure if that would work. Or I guess a configurable vertical size that is centered may work but we’d want the view to grow if it was bigger so it wouldn’t require scrolling (ours can become larger depending on error messages and factors of authentication required).

**Comment by twocanoes** [comment]
done. see current release.
