### ISSUE TITLE
Expansion of wiki preferences

### ISSUE THREAD

**Issue by kenchan0130** [twocanoes/xcreds#35]
When I look at https://github.com/twocanoes/xcreds/blob/develop/XCreds/TCSUnifiedLogger.m#L64 and https://github.com/twocanoes/xcreds/blob/develop/XCreds/PrefKeys.swift related source code, 
in https://github.com/twocanoes/xcreds/wiki/AdminGuide#preferences, we see some configuration items that we are unaware of. 

Are there any plans to add guides on these?

**Comment by twocanoes** [comment]
those were brought over from nomad login. i'll document as we implement and test.
