### ISSUE TITLE
Request: Add option to use the Mac Login Window as default

### ISSUE THREAD

**Issue by kryptonit1** [twocanoes/xcreds#40]
It would be nice if there was an option to use the Mac Login Window as the default login window instead of the XCreds Login window, but with the option to switch to the XCreds Login window if a new user that has not been logged on to the device needs to login for the first time.

**Comment by twocanoes** [comment]
added a new key "shouldShowCloudLoginByDefault" that is a boolean. see 

https://github.com/twocanoes/xcreds/wiki/AdminGuide#shouldshowcloudloginbydefault

added in 3292 or later
