### ISSUE TITLE
Latest build doesn't work on macOS versions pre-Monterey

### ISSUE THREAD

**Issue by benjaminhansen** [twocanoes/xcreds#42]
My team and I are testing out XCreds and we noticed that we can't get the latest build to run on any macOS versions earlier than 12 (Monterey).

<img width="435" alt="Screen Shot 2022-09-07 at 10 31 56 AM" src="https://user-images.githubusercontent.com/17499722/189023081-ff81b4f8-ad27-476d-b983-57601bc5374f.png">

<img width="389" alt="Screen Shot 2022-09-07 at 1 23 35 PM" src="https://user-images.githubusercontent.com/17499722/189023122-08775d46-7c1f-4f73-918b-77bb9ca9b61d.png">

[The docs](https://github.com/twocanoes/xcreds/wiki/AdminGuide#requirements) say it should be possible to run on earlier versions of macOS, so we're not sure if we've missed something or if the latest build was compiled specifically for macOS 12.3+ on purpose.

**Comment by twocanoes** [comment]
should work on macOS 11 and later now. thanks for reporting.
