### ISSUE TITLE
Request: Support using any claim as short name

### ISSUE THREAD

**Issue by kenchan0130** [twocanoes/xcreds#45]
In the current implementation, the short name uses the value set in username or the string before the `@` character in the email or unique name.

https://github.com/twocanoes/xcreds/blob/95e4719359ecb2105b829be4a3387a9f8079c304/XCredsLoginPlugIn/LoginWindow/LoginWebViewController.swift#L145-L175

However, some workloads may want to use other values of the ID Token object.
In the case of Jamf Connect, the ID Token object specified in the  `OIDCShortName` preference can be used as the short name.
See also: https://docs.jamf.com/jamf-connect/2.15.0/documentation/Login_Window_Preferences.html

**Comment by twocanoes** [comment]
check test PreBeta-XCreds_Build-3303_Version-2.2.pkg. Also, there is an update sample profile and manifest.
