### ISSUE TITLE
Xcreds not enable at restart

### ISSUE THREAD

**Issue by GitSweetDragon** [twocanoes/xcreds#47]
MAC OS 12 Monterey 
When user restart, login prompt for local account password. 
When user input login and pasword, he is again ask by input Azure AD login password (in our case) by xcreds. 
If cloud password isn't sync and user don't remember local password he can't anymore login Mac OS. 

from jam documentation for exemple : https://docs.jamf.com/jamf-connect/2.6.0/documentation/Passthrough_Authentication.html 

To enable passthrough authentication, use the Jamf Connect Configuration app or Jamf Pro's Application & Custom Settings payload to enable the Use Passthrough Authentication (OIDCUsePassthroughAuth) setting in a Jamf Connect login window configuration profile.
Azure AD
If you are using Azure AD, make sure the you also configure the Create a Separate Local Password (OIDCNewPassword) setting is to false.

```
<key>OIDCUsePassthroughAuth</key>
<true/>
<key>OIDCNewPassword</key>
<false/>

```

**Comment by twocanoes** [comment]
Passthrough is now working (try current release)
