### ISSUE TITLE
Login window doesn't remember Google username or permissions

### ISSUE THREAD

**Issue by cozturk** [twocanoes/xcreds#48]
Hi There,
First of all, thanks for all the work you've done to create this application. We try to set Xcreds to use at our school district and we successfully implemented the application. However, during the login page Google doesn't remember the username and during the every login attempt asks user's username, password, two-factor authentication code, and also the user to Allow or Deny the XCreds API permissions request. We followed the exact directions to create the API and also the profile so not sure what's the issue here. Thanks in advance to anyone who answers.

**Comment by twocanoes** [comment]
I believe this is correct behavior to prompt for all the information. The XCreds API permissions request was some debug code i left in and have now removed.
