### ISSUE TITLE
Debug notification says Azure when I'm using Google

### ISSUE THREAD

**Issue by bberkowitz** [twocanoes/xcreds#49]
Just learned about XCreds and am really enjoying it so far. Thanks for your great work.

Please see the screenshot. I used your sample xcreds_example_google.mobileconfig and modified it for my Google creds and enabled the showDebug flag and the notification refers to Azure as opposed to Google.

![IMG_9124](https://user-images.githubusercontent.com/4030382/193477958-1fcb4525-4082-462e-a14c-2cc5ad876da9.JPG)

**Comment by twocanoes** [comment]
i added notifications before logging to help troubleshoot. should i just remove the notifications or are they helpful?

**Comment by bberkowitz** [comment]
I think it's helpful, just threw me off. I think displaying Google when we're using Google would make sense.

**Comment by twocanoes** [comment]
OK, fixed in next build. Just changed to "password unchanged".
