### ISSUE TITLE
Issues with Intel - Restart&Shutdown Buttons Not Working

### ISSUE THREAD

**Issue by beckf** [twocanoes/xcreds#50]
Noticed a few issues when on an Intel Macbook Air. Creating an issue for each.

At the xcreds loginwindow, the restart and shutdown do not work.  This wasn't observed using the same deployment on Apple Silicon devices.

**Comment by twocanoes** [comment]
Just tried it and both worked fine. Can you give more information on the OS and how you set it up?

**Comment by beckf** [comment]
Clearly it is something weird on our end then.  Thanks for verifying for me.

**Comment by beckf** [comment]
Confirmed it was our problem. Again sorry for the false alert.
