### ISSUE TITLE
Issues with Intel - Some users unable to login via xcreds

### ISSUE THREAD

**Issue by beckf** [twocanoes/xcreds#51]
Noticed a few issues when on an Intel Macbook Air. Creating an issue for each.

Any user that is a staff member (firstname.lastname@domain.tld) cannot login to xcreds through Azure on an Intel based machine.

In Azure,we have students that have an email address/upn that matches their username (samaccountname).  Staff have a firstname.lastname email address/upn that doesn't match their samaccountname.  I haven't been able to identify which (if any) of these two conditions are causing this.  

This is ONLY observed on an Intel computer.  A computer with Apple Silicon using same deployment doesn't have this issue.

Logs from /tmp:

FILE:PasswordUtils.swift LINE:271 FUNCTION:getLocalRecord(_:) No local user found. Passing on demobilizing allow login.
FILE:PasswordUtils.swift LINE:277 FUNCTION:getLocalRecord(_:) ODError while trying to check for local user: %{public}@
FILE:LoginWebViewController.swift LINE:282 FUNCTION:tokensUpdated(tokens:) updating username:forrest.beck, password, and tokens
FILE:XCredsLoginMechanism.swift LINE:121 FUNCTION:allowLogin() Allowing Login
FILE:XCredsLoginMechanism.swift LINE:123 FUNCTION:allowLogin() Dismissing controller
FILE:XCredsLoginMechanism.swift LINE:127 FUNCTION:allowLogin() calling super allowLogin
FILE:XCredsBaseMechanism.swift LINE:139 FUNCTION:allowLogin() allowLogin() /Users/tperfitt/Documents/Projects/xcreds/XCredsLoginPlugIn/Mechanisms/XCredsBaseMechanism.swift:139
 MechanismInvoke /Users/tperfitt/Documents/Projects/xcreds/XCredsLoginPlugIn/XCredsLoginPlugin.m:37
 -[XCredsLoginPlugin MechanismInvoke:] /Users/tperfitt/Documents/Projects/xcreds/XCredsLoginPlugIn/XCredsLoginPlugin.m:123
FILE:XCredsBaseMechanism.swift LINE:20 FUNCTION:init(mechanism:) init(mechanism:) /Users/tperfitt/Documents/Projects/xcreds/XCredsLoginPlugIn/Mechanisms/XCredsBaseMechanism.swift:20
FILE:XCredsBaseMechanism.swift LINE:48 FUNCTION:setupPrefs() -------------------------------------
FILE:XCredsBaseMechanism.swift LINE:49 FUNCTION:setupPrefs() XCreds Login Build Number: 3291
FILE:XCredsBaseMechanism.swift LINE:50 FUNCTION:setupPrefs() -------------------------------------
FILE:XCredsLoginMechanism.swift LINE:93 FUNCTION:run() run() /Users/tperfitt/Documents/Projects/xcreds/XCredsLoginPlugIn/Mechanisms/XCredsLoginMechanism.swift:93

**Comment by twocanoes** [comment]
I created a betty.rubble@twocanoes.com account in Azure AD. Installed XCreds on intel mac. logged in fine (provisioned user as well).

**Comment by beckf** [comment]
So strange. I am unable to login with users that are first.last@domain.org, but any user that is shortusername@domain.org works. Azure SignIn logs show success for both.

**Comment by beckf** [comment]
This was related to our previous issue as well. Sorry for the false report.
