### ISSUE TITLE
Add support for Enterprise Auth Wi-Fi 

### ISSUE THREAD

**Issue by iamlenhall** [twocanoes/xcreds#53]
We are unable to connect to our employee Wi-Fi via xcreds. We use enterprise Auth Wi-Fi.

**Comment by DoubleM-DCDSB** [comment]
Yes support for 802.1x would be great.

**Comment by PeetMcK** [comment]
Just adding a +1

**Comment by ntauthy** [comment]
+1

**Comment by stiebke** [comment]
+1

**Comment by lauramcj2015** [comment]
+1

**Comment by mariuslangz** [comment]
+1

**Comment by twocanoes** [comment]
this is in 3.0. it requires the identity to be in the system keychain.
