### ISSUE TITLE
Request: display user password expiration (days left or specific date) in app. I've seen this in Kerberos SSO and I believed NoMad.

### ISSUE THREAD

**Issue by iamlenhall** [twocanoes/xcreds#54]

**Comment by remusache** [comment]
Yes!!!
I was about to ask the same… 😋

**Comment by 1sth1sth1ng0n** [comment]
This would be huge! @twocanoes. For Azure - you can get the pwdLastSet attribute into the the token via a custom claim. Then set some logic around that to figure out the expiry time. Password validity time could also be defined as a preference then just count down from there, but you would need to ensure the password is always updated via XCreds.
