### ISSUE TITLE
Cloud Login window not available when macOS login window is set as default

### ISSUE THREAD

**Issue by kevaru** [twocanoes/xcreds#55]
When `shouldShowCloudLoginByDefault` key is set to `false`, the macOS login window with the Cloud Login Button in the left bottom section appears correctly after booting but when clicking the Cloud Login button, the 'This may take 30 seconds.. ' warning turns up, screen goes black and after about 5 seconds, the regular macOS login window reappears without the Cloud Login button. It's not possible to get to the Cloud-Login window. 

Affected releases: PreBeta-XCreds_Build-3300, PreBeta-XCreds_Build-3301. 

Tested with freshly reset Mac running Monterey 12.6.

**Comment by DoubleM-DCDSB** [comment]
I can also confirm this. After this is enabled the Cloud login button does not reappear.

**Comment by twocanoes** [comment]
Fixed in PreBeta-XCreds_Build-3328_Version-2.2.pkg or later.
