### ISSUE TITLE
Feature Request: Specify certain users to create as Admin, create all others as standard

### ISSUE THREAD

**Issue by georgecm12** [twocanoes/xcreds#56]
Currently, it appears that Xcreds has a global plist setting, "CreateAdminUser," that defines whether to create all users as either standard user or as an administrator user. 

As a feature request, it would be nice to be able to define a list of specific user name(s) that should be created as with administrator permissions, while all other users are created as standard users. This would be desirable to elevate specific IT staff to administrators whenever they log in on client machines, while leaving other users as standard users.

**Comment by twocanoes** [comment]
would it be part of an OIDC claim or user names hardcoded in the prefs?

**Comment by georgecm12** [comment]
Either would be an acceptable option. Having limited access to Azure and having to go through a different team for that, prefs would be easier for me personally, but OIDC seems like it could be potentially more scalable. I can go either way.

**Comment by PeetMcK** [comment]
My vote would be for OIDC as well.

**Comment by cotisimo** [comment]
My vote would be for OIDC!  This feature would spark joy...

**Comment by twocanoes** [comment]
implemented
