### ISSUE TITLE
Feature request: support for Azure samAccountName

### ISSUE THREAD

**Issue by pekkasalonen** [twocanoes/xcreds#57]
I'm asking for a single additional claim, "samAccountName" to be used as additional basis for local username, after "defaultsUsername" and before "email". 

Or the same thing with some other claim name that does not conflict with standard Azure ID token claims. As far as I know, Azure admins use powershell diddlery to add username into the token, and so in the process can change the claim title. But can't take over reserved "unique_name", for example. Anyway "samAccountName" is a good claim name for samAccountName or onPremisesSamAccountName.

This is a simpler ask than #45 or #52 where the name of the claim would be a preference setting. If that is implemented, this one is solved as well of course.

**Comment by pekkasalonen** [comment]
I learn that `IDToken:Codable` allows for fancy mapping with equal sign. Sad that the fields need to be known at compile time, otherwise would have been smooth way to add custom claim from preference manifest. At least makes it clean to unify variable naming style. Like in TokenManager.swift:

`case iss,sub,aud,name,given_name,family_name,email,iat,exp,unique_name,sam_accout_name = "samAccountName"'`

(Or do you use `name` for anything?)

Then in LoginWebViewController.swift:
```
if let defaultsUsername = defaultsUsername {
            username = defaultsUsername
}
else if idTokenObject.sam_account_name != nil {				//// 
	        username = idTokenObject.sam_account_name!		////
}
else {
    var emailString:String
    if idTokenObject.email != nil {
        emailString=idTokenObject.email!.lowercased()
    }
    else if idTokenObject.unique_name != nil {
        emailString=idTokenObject.unique_name!
    }
    else {
...
```


Not sure if something needs to be done elsewhere, like with setHint, so not attempting a pull request.

**Comment by beckf** [comment]
This is the same request as #45 and #52 . All are looking for support using sAMAccountName in some way. We use JAMF Connect now and have added the onpremisesamaccountname to the claim.  So the field is already being sent.  We just need a way to tell xcreds to use it through config profile.

**Comment by pekkasalonen** [comment]
@beckf Yes yes, _in spirit_ this is same as #45 and #52, this is what we "all" want. Yep, username cut from email is a show stopper for me. _In execution_ this would be a subset of those and would be way smaller and cleaner change.

For example, I made a quite crude implementation of #45 and #52 and was even cocky enough to make a pull request (as #46), now closed. Not pretty, even though _seems_ to work. What I'm suggesting now instead is a change of about 3 lines (I hope). Not much more anyway.

(I don't use either change in my test Macs anymore, I use even simpler but somewhat breaky change of one word:
`case iss,sub,aud,name,given_name,family_name,email="samAccountName",iat,exp,unique_name`
because it works for me.)

**Comment by twocanoes** [comment]
thanks for the code. I didn't end up using it, but it did lead me down the right path. check test PreBeta-XCreds_Build-3303_Version-2.2.pkg. Also, there is an update sample profile and manifest.
