### ISSUE TITLE
Feature Request: Force Wi-Fi on option or Wi-Fi on/off switch in "Configure Wi-Fi"

### ISSUE THREAD

**Issue by PeetMcK** [twocanoes/xcreds#58]
Request Summary: Add setting to turn Wi-Fi "on" if "off" when "Configure Wi-Fi" is selected or ad a Wi-Fi on/off switch to "Configure WiFi".

Existing behavior:  "Configure Wi-Fi" does not report the state of the Wi-Fi adapter. If it's off, the UI looks as though it's on, but no SSID's can be discovered. There's no mechanism to turn it on, or ensure it's on.

Feature Request:  First, UI provide feedback that Wi-Fi is "off". But the feature could be addressed in multiple ways. 

- A setting that automatically turns the Wi-Fi interface "on" if off when accessing "Configure Wi-Fi".
- A toggle switch within "Configure Wi-Fi" to turn the WI-Fi interface on/off.
- Auto-Enable Wi-Fi when "Configure Wi-Fi" and no wan connected interface are detected.

Any one or a combination of the above would solve the issue of needing an SSO login, but Wi-Fi is off.

**Comment by SteveTory** [comment]
I'd like to also request this feature!
