### ISSUE TITLE
Feature Request: add "authchanger"-like "-reset" option to "xcreds_login.sh"

### ISSUE THREAD

**Issue by PeetMcK** [twocanoes/xcreds#61]
**Request Summary:** `authchanger` has two primary features when used in context with NoMAD LoginAD. `authchanger -reset` and `authchanger -AD`. `-reset` configures auth.db back to "Factory Defaults". `-AD` configures the required authentication rights for NoMAD LoginAD. Consequently an `authchanger -reset -AD` ensures that only NoMAD LoginAD has authentication rights in auth.db. 

A similar `xcreds_login.sh -d -i` (`-d` for "defualt") would be incredibly helpful and would allow for a simple method of ensuring a known-good XCreds configuration. 

**Existing Behavior:** `xcreds_login.sh -i` does configure XCreds correctly from a default state, but if another authentication plugin like NoMAD LoginAD is configured, the auth mechanism list is mangled mangled. As a work around using `authchanger -reset` then `xcreds_login.sh -i` produces a known-good configuration. 

**Feature Request:** building a `-d` "defaults" function into 'xcreds_login.sh' would allow for ensuring a known-good authentication mechanism state without relying on a tool like `authchanger` from another project.

**Comment by twocanoes** [comment]
xcreds_login.sh is a shell script so you can see how it is working and create your own. authrights is the tool that actually changes the rights. Here is what it does:

        "${authrights_path}" -r "loginwindow:login" "XCredsLoginPlugin:LoginWindow"
        "${authrights_path}" -a  "XCredsLoginPlugin:LoginWindow" "XCredsLoginPlugin:PowerControl,privileged"
        "${authrights_path}" -a  "loginwindow:done" "XCredsLoginPlugin:KeychainAdd,privileged"
        "${authrights_path}" -a  "builtin:login-begin" "XCredsLoginPlugin:CreateUser,privileged"
        "${authrights_path}" -a  "loginwindow:done" "XCredsLoginPlugin:EnableFDE,privileged"
        "${authrights_path}" -a  "loginwindow:done" "XCredsLoginPlugin:LoginDone"

I am wondering if it would be better for you to craft a script that would put the rights in the correct places, or at least cleanup after mangling. Not saying I don't want to fix it, just want to make it applicable to all.

**Comment by hurricanehrndz** [comment]
XCreds also makes a backup that can be restored
```
security authorizationdb write system.login.console <  /Library/"Application Support"/xcreds/rights.bak
```
