### ISSUE TITLE
Feature Request: Local User Account Picker

### ISSUE THREAD

**Issue by ntauthy** [twocanoes/xcreds#63]
I'd like to request a feature at the login screen (similar to JConnect) that lets the user pick which user account to have xcreds manage. We use google workspace and we are not able to create custom claims like you can in azure so we have no way to map a local user account to a google workspace user when the local user account does not match first initial, last name format (eg. JSmith). We would LOVE this feature as currently its a blocker to being able to roll this out company-wide as we have about 100 machines that don't match the naming convention. (We would gladly pay for paid support if we could expedite this feature as well!)

**Comment by dalonfoley** [comment]
This would be awesome! literally the only thing holding me back from deployment.

**Comment by twocanoes** [comment]
dup of #98 . added.
