### ISSUE TITLE
XCreds Verifies Cloud Password at Sign-in

### ISSUE THREAD

**Issue by anderb54** [twocanoes/xcreds#64]
After changing the password on Google, if the user signs in at the cloud login screen, they are asked to verify their password, even though the "Verify Cloud Password" profile is set to false. When clicking on the verify popup box it disappears and you can't ever verify.

The Verify Cloud Password profile setting set to false works perfectly when signed it.

<img width="1427" alt="LWScreenShot 2023-01-30 at 10 09 31 AM" src="https://user-images.githubusercontent.com/123972146/215539007-918d2f60-3f6a-420a-89e8-36ca89710018.png">

**Comment by mariuslangz** [comment]
We've seen the same thing happening when using Azure!

Oh, and also found another annoying bug: If you click outside that verify cloud password box by a mistake, it hides behind the login-window and we cannot click on anything... Seems that we need to forcefully restart the Mac to get anywhere.

**Comment by anderb54** [comment]
The developer has released a PreBeta that is supposed to help with this. I haven't had much luck testing yet.

https://macadmins.slack.com/archives/C03GBF2DE7P/p1675443093637089

**Comment by twocanoes** [comment]
is this still happening? I have not heard reports of it as of late.

**Comment by anderb54** [comment]
No, that issue has gone away for me at least with 3.0. However, that new popup includes the reset button which is great but if I click reset it takes me back to the Mac login screen and doesn't allow me to sign-in with the new password.
![IMG_1315](https://github.com/twocanoes/xcreds/assets/123972146/f9971840-68a6-4c6c-a0c5-99648964f586)

**Comment by twocanoes** [comment]
please check with latest beta of version 4.
