### ISSUE TITLE
XCreds unable to check password if Wifi is slow...

### ISSUE THREAD

**Issue by everetteallen** [twocanoes/xcreds#66]
We see an issue where the password check fails (with debug on get notification saying  XCreds can't check) when the Wifi (or whatever) network is slow to respond.
In our environment the WiFi will sometimes take several seconds to stabilize as is evidenced by the menu bar indicator flashing(the round trip for our eduroam verification can be long).
During this time XCreds with attempt to check if the local password is in sync and fail due to no network as evidenced by the green dot not appearing in the menu bar icon. Quitting and restarting the menu bar app will yield correct results (usually confirm sync is good with green dot) as will using the refresh menu.
Is it possible to have XCreds wait for the network ?  Launch agents used to have a setting that would do this.

**Comment by twocanoes** [comment]
URLSession timeout by default is 60 seconds. Is it possible that it is taking longer than 60 seconds?

**Comment by twocanoes** [comment]
please verify it still occurs in XCreds 4 and reopen as needed.
