### ISSUE TITLE
Add Prestage scripting option

### ISSUE THREAD

**Issue by charliwest** [twocanoes/xcreds#67]
Hello, I would love to see a feature added that would let you run SwiftDialog (or other versions, like DEPNotify etc) after the prestage xcreds but before the user logs in, like how Jamf Connect can run Jamf Notify (which is basically just DEPNotify). This would allow a device to be fully configured before the desktop appears for the user. 

Thanks for yet another great app/product!

**Comment by hurricanehrndz** [comment]
I believe this would be better handle by a launch daemon that awaits for the Desktop. Is there a particular reason you wish to notify before the user is created and before the desktop?

**Comment by twocanoes** [comment]
I don't really understand this issue. Is it for provisioning the user prior to anyone logging in?

**Comment by twocanoes** [comment]
no response. closing.
