### ISSUE TITLE
"Trial Version" banner at login screen

### ISSUE THREAD

**Issue by georgecm12** [twocanoes/xcreds#71]
Xcreds 2.4 (3504) currently displays a "Trial Version" banner. 

It's my understanding that the new paid licensing only applies to version 3.0 and above, so one assumes that there should be a way to remove this "trial version" banner in 2.4.

**Comment by Criseld** [comment]
Hi! Is there any update on this? Can the "Trial" banner be removed in 2.4?

**Comment by twocanoes** [comment]
The trial banner is 2.4 can be removed by setting a preference key. Set shouldShowSupportStatus to false.
