### ISSUE TITLE
loginWindowBackgroundImageURL image should be cached if not a file:// URL

### ISSUE THREAD

**Issue by macprince** [twocanoes/xcreds#72]
I have the `loginWindowBackgroundImageURL` in XCreds configured to a URL on a web server. I've noticed that if the network is still coming up when XCreds Login is coming up, it can't reach the web server and the default image is used instead. 
Could XCreds cache the image from this URL and reference the cached file if the URL is not reachable when XCreds Login loads?

**Comment by twocanoes** [comment]
is this still wanted given that the default image is now macOS default? The easiest way to implement is just just have a the image as data in the config profile.

**Comment by macprince** [comment]
@twocanoes Not entirely sure what you mean by this. I need to embed the image in the config profile?

**Comment by twocanoes** [comment]
yes, nomad did this. you put in as base64. would that suffice?

**Comment by twocanoes** [comment]
case BackgroundImage
    /// An image to display as the background image as a Base64 encoded `String`.

**Comment by twocanoes** [comment]
it is isn't defined but it does work.

**Comment by twocanoes** [comment]
please test and reopen if it is doesn't work for you.

**Comment by macprince** [comment]
Embedding the image itself in the config profile isn't really the solution I'm looking for. By defining a URL to the image, I can change the image easily on the web server and have all of the clients get it from there. I don't know what my MDM's file size limit for uploaded profiles is, and I'd have to base64 encode the image any time I want to change it.
Is caching the image retrieved from the defined URL a troublesome thing to implement?

**Comment by twocanoes** [comment]
implemented.
