### ISSUE TITLE
Feature Request: Allow uid mapping from OIDC Claim

### ISSUE THREAD

**Issue by belfhi** [twocanoes/xcreds#74]
Hi,
we have setup where we would like to map the unix uid 
that the user has from an OIDC Claim.
We use Keycloak as an IdP, so we are free to add custom claims
and such can map the uid from the backend (LDAP in this case) to the
access_token etc.
Could this be done with xCreds in a similar way that the username is
mapped from an OIDC claim?

**Comment by twocanoes** [comment]
There some risk in this. let me know if it is still needed.

**Comment by mallej** [comment]
https://github.com/twocanoes/xcreds/issues/186
