### ISSUE TITLE
Create Admin User when logged in using Domain login

### ISSUE THREAD

**Issue by bstep1** [twocanoes/xcreds#75]
In 3.1 the ability to create a user as an Admin based on their OID Groups was added.  

If a user logs in for the first time using the Domain login instead of IdP the user's groups are not evaluated to create the user as an admin.  Further if the user then logs in with the IdP login, since their account already exists it does not create as an admin user when they are a member of the admin groups.

As a feature request, when logging in with a Domain login it would be nice if the user's groups were checked against a list to see if the user should be created as an Admin user.  Users not in the list would be created as standard users.

**Comment by twocanoes** [comment]
implemented in build 5568 or later.
