### ISSUE TITLE
Option to write certain claims to a plist

### ISSUE THREAD

**Issue by kcrawford** [twocanoes/xcreds#76]
Would be nice to have a setting for an array of strings of claims keys that can be written out to a plist for other software and scripts to use for configuring email and other applications. And maybe a setting for whether to write claims out to the plist (default false). If true it writes the claims listed in the above key array otherwise it writes all claims.

**Comment by twocanoes** [comment]
The idToken is written to the keychain. Would that be enough?

**Comment by kcrawford** [comment]
Reading from keychain is a not ideal because it requires the user to enter their password to allow access right? Or is it set to allow all applications?

**Comment by twocanoes** [comment]
It is only allowed by XCreds and other apps are prompted. I'll look into creating the plist.

**Comment by kcrawford** [comment]
Thanks. Writing into local account attributes might also be a good alternative like a mobile account would . I thinks XCreds already writes some attributes there.

**Comment by twocanoes** [comment]
now written to DS per other issue. Closing.
