### ISSUE TITLE
Sonoma Developer Beta 2 - Black Login Screen

### ISSUE THREAD

**Issue by keithmedlin** [twocanoes/xcreds#77]
After upgrading to Sonoma Developers Beta 2 the login screen is black. In the lower-left corner the “Cloud Login” link is visible. When clicked, the 30 second warning appears. After about 15-20 seconds it disappears the screen returns to being completely black.

**Comment by twocanoes** [comment]
thanks. we will be testing Sonoma soon.

**Comment by Mavyre** [comment]
I can confirm the black screen on Sonoma (non-beta)

**Comment by davelebbing** [comment]
Could not replicate black screen when upgrading Ventura to Sonoma with XCreds using the following preference keys.  If any other preference keys may be involved, please mention in comments.

- clientID
- discoveryURL
- redirectURI
- shouldShowCloudLoginByDefault:false

**Comment by Mavyre** [comment]
To be honest, I had once the black screen issue. Now there just is a black screen for 5-10 seconds, then the Google Login shows up

**Comment by twocanoes** [comment]
Found a way to replicate something similar to this issue.  If so it is likely this would be fixed by XCreds version 3.2 (build 5197 currently prebeta but targeted for release very soon).  Available from Github releases page: https://github.com/twocanoes/xcreds/releases/tag/prebeta
