### ISSUE TITLE
Admin Group setting uses object ID instead of name

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#80]
The setting for CreateAdminIfGroupMember works for Azure if the value is set as the object ID of the group rather than the group name.  This is ok but if possible may be better if refactored to use group name instead of ID if the name value is returned in the authentication payload.  If this is not possible then it may be best to clarify this in the manifest plist description.

**Comment by twocanoes** [comment]
changed description to:

			<string>List of groups that should have its members created as local administrators. Set as an Array of Strings of the group identifier.</string>


as of 5078
