### ISSUE TITLE
Conflict for shouldSwitchToLoginWindowWhenLocked with shouldShowCloudLoginByDefault

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#82]
There appears to be a conflict with setting shouldSwitchToLoginWindowWhenLocked to true when shouldShowCloudLoginByDefault is set to false.  When this is done and a user locks the screen with XCreds running, the screen will momentarily hang when switching to the lock screen.  Then when the user authenticates and returns to their session it appears that anything running was stopped and not allowed to continue running.

**Comment by twocanoes** [comment]
should be resolved as of 5078. please verify.
