### ISSUE TITLE
Fix documentation link for autoRefreshLoginTimer

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#85]
In the manifest plist in the section for autoRefreshLoginTimer the documentation url has the wrong anchor component.  

Change: 

https://github.com/twocanoes/xcreds/wiki/AdminGuide#cloudlogintext

to: 

https://github.com/twocanoes/xcreds/wiki/AdminGuide#cloudlogintimer

**Comment by twocanoes** [comment]
fixed in 5078 or later

**Comment by davelebbing** [comment]
I put the wrong documentation url anchor value above.  To match the existing pattern the anchor should be the value for "pfm_name".  So change this:

https://github.com/twocanoes/xcreds/wiki/AdminGuide#cloudlogintimer

To this: 

https://github.com/twocanoes/xcreds/wiki/AdminGuide#autorefreshlogintimer
