### ISSUE TITLE
Potential problem with setting for autoRefreshLoginTimer and switch login window

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#89]
When logging into macOS using the cloud login window and then clicking the button at the bottom of the screen to switch the login window, the setting for autoRefreshLoginTimer can result in this going back to the cloud login window.  This becomes an issue if autoRefreshLoginTimer is set very low and the cloud login webview refreshes frequently.  But this also show that when the cloud login webview refresh occurs it switches back to showing the cloud login webview.  If the user clicks the button to switch to the local login window it could be good to avoid having the cloud login webview refresh event change which login window is displayed.

**Comment by davelebbing** [comment]
Issue still present in v3.2 b5197

**Comment by twocanoes** [comment]
@davelebbing Please show me

**Comment by twocanoes** [comment]
fixed in 4. please verify.
