### ISSUE TITLE
Update documented minimum for loginWindowWidth and loginWindowHeight

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#91]
The documented minimum value for loginWindowWidth and loginWindowHeight may need to be updated.  When setting these  settings to their minimum value of 100 the cloud login webview is displayed full screen.  Increasing these values to 200 does show as expected with the webview being displayed very small.  The effective minimum value appears to be somewhere between 100 and 200.

**Comment by twocanoes** [comment]
minimum value was 101. Changed to 150.
