### ISSUE TITLE
Issue when signing out with no network connection

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#92]
If wifi is disabled and a user signs out of macOS the machine appears to hang and does not return to the XCreds sign in window until network access is restored or the machine is restarted.

**Comment by davelebbing** [comment]
Found this is probably ok and maybe only related to testing in VM and self-signed IP.  Tested again by going to macOS settings in VM > Network > Ethernet > Make Inactive.  After doing this and signing out the XCreds cloud login window was shown as expected with a network status message and sign in could be completed by switching the sign in window and signing in locally.

**Comment by mallej** [comment]
I still see this problem even on a M2 MacBook Air.
