### ISSUE TITLE
Login window space characters not being stripped 3.1

### ISSUE THREAD

**Issue by sccmrb** [twocanoes/xcreds#95]
In NoMAd login we had an issue where putting in a space character was ignored by the login process but passed onto the Mac as a new user.  So "username" and " username" and "username " are both valid with the same password and it creates three separate users.  This was a massive headache for us last year with NoMAD Login.

**Comment by sccmrb** [comment]
Forgot to add, this problem still exists in XCreds 3.1.  In the NoMAD login files it was in the UI file that contained the bug for not filtering out space characters.

**Comment by sccmrb** [comment]
I'm thinking around line 131 of the NoLoMechanism.swift file is the issue in not stripping space characters.

**Comment by twocanoes** [comment]
I'll add in a fix and create a new build

**Comment by twocanoes** [comment]
It was actually in XCredsBaseMechanism. I stripped out whitespace and \0. New build is up:
PreBeta-XCreds_Build-5085_Version-3.2.pkg

**Comment by sccmrb** [comment]
Ok great, thanks.  I will verify tomorrow 8/4 when I'm back on campus.

**Comment by sccmrb** [comment]
It still appears to still be creating a user but when you attempt to login it just freezes the login screen

**Comment by sccmrb** [comment]
When looking in the local directory utility on the computer the user that's created has the spaces in it still.  In this case we are using a user called "teststudent" but I logged in as "   teststudent". Two users now are in the Users section of System Settings but it's not actually creating the home folder.  Can we stop the login process if it has a space at all?

**Comment by twocanoes** [comment]
OK, i'l dig into it. I cleaned up the code that stripped the nulls to also strip spaces, but there seems to be more to it.

**Comment by twocanoes** [comment]
i added additional normallization and hopefully it will resolve the issue. See build PreBeta-XCreds_Build-5087_Version-3.2.pkg

**Comment by sccmrb** [comment]
Ahh excellent.  That seems to have done it.  I tired a few users with and without spaces and no new accounts were created.  Thank you very much.
