### ISSUE TITLE
invalid characters

### ISSUE THREAD

**Issue by twocanoes** [twocanoes/xcreds#96]
The password we had set for the localadminpassword had ampersand (&) characters which was causing issues. We tried a couple of different options, but ultimately, we used a password with no special characters, as several of the alternative characters we tested caused an issue either in the script or in the XML validation. I just wanted to raise this with you so you can provide notice in your documentation. To get it to work we have used a 20 character alphanumeric, non-special-character password.

**Comment by twocanoes** [comment]
I think this was not related to xcreds but how the scripts returns/does SED/AWK etc. @davelebbing please test and see if using an "&" in a username is problem

**Comment by davelebbing** [comment]
No issues found with ampersand in password when signing in using XCreds.
