### ISSUE TITLE
Profile for Azure XCreds needs updating to include values appropriate for Azure OIDC Claims

### ISSUE THREAD

**Issue by TreeBranches** [twocanoes/xcreds#97]
Discussed here;
https://macadmins.slack.com/archives/C03GBF2DE7P/p1690468998167369

Default values should be more appropriate for MacOS Username conventions, as currently the default values grab the display name, causing the user's home folder to potentially have unexpected characters (ie, a character outside of the a-z, A-Z, 0-9 scope, or a space between first name and surname).

- The `map_firstname` entry should be `user.givenName` and not `given_name`
- The `map_lastname` entry should be `user.surname` and not `family_name`
- The `map_fullname` entry should be `user.displayName` and not `name`
- The `map_username` entry should be `user.userprincipalname` and not `name`

**Comment by twocanoes** [comment]
no response. closing.
